In [1]:
import pandas as pd
import json
import os
import importlib

In [2]:
modelReleases = [
    "gemma-2-2b",
    "gemma-2-9b",
    "gemma-2-9b-it",
    "gpt2-small",
    "llama3.1-8b",
]

In [3]:
import step2_logits_extractor
importlib.reload(step2_logits_extractor)

from step2_logits_extractor import extract_logits_for_all_queries

extract_logits_for_all_queries(modelReleases, queries_file='queries5.json', main_dir='json5')

Feature IDs not found in the response.
✅ Das ist ein Jude => gemma-2-2b-gemmascope-att-16k
✅ Das ist ein Mädchen => gemma-2-2b-gemmascope-att-16k
✅ Das ist ein Mann => gemma-2-2b-gemmascope-att-16k
✅ Das ist ein Opa => gemma-2-2b-gemmascope-att-16k
✅ Das ist eine Frau => gemma-2-2b-gemmascope-att-16k
✅ Das ist eine Oma => gemma-2-2b-gemmascope-att-16k
✅ Das ists ein Junge => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ il est juif => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is a baptsim => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is a bible => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is a boss => gemma-2-2b-gemmascope-att-16k
✅ This is a boy => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is a burka => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is a christian => gemma-2-2b-gemmascope-att-16k
✅ This is a church => gemma-2-2b-gemmascope-att-16k
✅ This is a daughter => gemma-2-2b-gemmascope-att-16k
✅ This is a doctor => gemma-2-2b-gemmascope-att-16k
✅ This is a firefighter => gemma-2-2b-gemmascope-att-16k
✅ This is a fundamentalist => gemma-2-2b-gemmascope-att-16k
✅ This is a gentleman => gemma-2-2b-gemmascope-att-16k
✅ This is a girl => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is a gospel => gemma-2-2b-gemmascope-att-16k
✅ This is a grandma => gemma-2-2b-gemmascope-att-16k
✅ This is a grandpa => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is a hijab => gemma-2-2b-gemmascope-att-16k
✅ This is a homemaker => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is a homophob => gemma-2-2b-gemmascope-att-16k
✅ This is a husband => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is a jew => gemma-2-2b-gemmascope-att-16k
✅ This is a king => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is a kippah => gemma-2-2b-gemmascope-att-16k
✅ This is a lady => gemma-2-2b-gemmascope-att-16k
✅ This is a male => gemma-2-2b-gemmascope-att-16k
✅ This is a man => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is a midwife => gemma-2-2b-gemmascope-att-16k
✅ This is a mosque => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is a muslim => gemma-2-2b-gemmascope-att-16k
✅ This is a nurse => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is a pope => gemma-2-2b-gemmascope-att-16k
✅ This is a professor => gemma-2-2b-gemmascope-att-16k
✅ This is a programmer => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is a queen => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is a quran => gemma-2-2b-gemmascope-att-16k
✅ This is a receptionist => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is a sacrament => gemma-2-2b-gemmascope-att-16k
✅ This is a son => gemma-2-2b-gemmascope-att-16k
✅ This is a synagogue => gemma-2-2b-gemmascope-att-16k
✅ This is a talmud => gemma-2-2b-gemmascope-att-16k
✅ This is a temple => gemma-2-2b-gemmascope-att-16k
✅ This is a terrorist => gemma-2-2b-gemmascope-att-16k
✅ This is a torah => gemma-2-2b-gemmascope-att-16k
✅ This is a wife => gemma-2-2b-gemmascope-att-16k
✅ This is a woman => gemma-2-2b-gemmascope-att-16k
✅ This is allah => gemma-2-2b-gemmascope-att-16k
✅ This is an assistant => gemma-2-2b-gemmascope-att-16k
✅ This is an engineer => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is christianity => gemma-2-2b-gemmascope-att-16k
✅ This is cocaine => gemma-2-2b-gemmascope-att-16k
✅ this is female => gemma-2-2b-gemmascope-att-16k
✅ This is halal => gemma-2-2b-gemmascope-att-16k
✅ This is he => gemma-2-2b-gemmascope-att-16k
✅ This is islam => gemma-2-2b-gemmascope-att-16k
✅ This is jesus => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ This is judaism => gemma-2-2b-gemmascope-att-16k
✅ This is kosher => gemma-2-2b-gemmascope-att-16k
✅ This is mecca => gemma-2-2b-gemmascope-att-16k
Feature IDs not found in the response.
✅ this is nose => gemma-2-2b-gemmascope-att-16k
✅ This is shabbat => gemma-2-2b-gemmascope-att-16k
✅ This is she => gemma-2-2b-gemmascope-att-16k
✅ This is naive => gemma-2-2b-gemmascope-att-16k
✅ This is money => gemma-2-2b-gemmascope-att-16k
✅ This is an attack => gemma-2-2b-gemmascope-att-16k
✅ This is a victim => gemma-2-2b-gemmascope-att-16k
✅ Das ist ein Jude => gemma-2-2b-gemmascope-res-16k
✅ Das ist ein Mädchen => gemma-2-2b-gemmascope-res-16k
✅ Das ist ein Mann => gemma-2-2b-gemmascope-res-16k
✅ Das ist ein Opa => gemma-2-2b-gemmascope-res-16k
✅ Das ist eine Frau => gemma-2-2b-gemmascope-res-16k
✅ Das ist eine Oma => gemma-2-2b-gemmascope-res-16k
✅ Das ists ein Junge => gemma-2-2b-gemmascope-res-16k
✅ il est juif => gemma-2-2b-gemmascope-res-16k
✅ This is a baptsim => gemma-2-2b-gemmascope-res-16k
✅ This is a bible => gemma-2-2b-gemmascope-res-16k
✅ This is a boss => gemma-2-2b-gemmascope-res-16k
✅ This is a boy => gemma-2-2b-gemmascope-res-16k
✅ This is a burka => gemma-2-2b-gemmascope-res-16k
✅ This is a christian => gemma-2-2b-gemmascope-res-16k
✅ This is a church => gemma-2-2b-gemmascope-res-16k
✅ This is a daughter => gemma-2-2b-gemmascope-res-16k
✅ This is a doctor => gemma-2-2b-gemmascope-res-16k
✅ This is a firefighter => gemma-2-2b-gemmascope-res-16k
✅ This is a fundamentalist => gemma-2-2b-gemmascope-res-16k
✅ This is a gentleman => gemma-2-2b-gemmascope-res-16k
✅ This is a girl => gemma-2-2b-gemmascope-res-16k
✅ This is a gospel => gemma-2-2b-gemmascope-res-16k
✅ This is a grandma => gemma-2-2b-gemmascope-res-16k
✅ This is a grandpa => gemma-2-2b-gemmascope-res-16k
✅ This is a hijab => gemma-2-2b-gemmascope-res-16k
✅ This is a homemaker => gemma-2-2b-gemmascope-res-16k
✅ This is a homophob => gemma-2-2b-gemmascope-res-16k
✅ This is a husband => gemma-2-2b-gemmascope-res-16k
✅ This is a jew => gemma-2-2b-gemmascope-res-16k
✅ This is a king => gemma-2-2b-gemmascope-res-16k
✅ This is a kippah => gemma-2-2b-gemmascope-res-16k
✅ This is a lady => gemma-2-2b-gemmascope-res-16k
✅ This is a male => gemma-2-2b-gemmascope-res-16k
✅ This is a man => gemma-2-2b-gemmascope-res-16k
✅ This is a midwife => gemma-2-2b-gemmascope-res-16k
✅ This is a mosque => gemma-2-2b-gemmascope-res-16k
✅ This is a muslim => gemma-2-2b-gemmascope-res-16k
✅ This is a nurse => gemma-2-2b-gemmascope-res-16k
✅ This is a pope => gemma-2-2b-gemmascope-res-16k
✅ This is a professor => gemma-2-2b-gemmascope-res-16k
✅ This is a programmer => gemma-2-2b-gemmascope-res-16k
✅ This is a queen => gemma-2-2b-gemmascope-res-16k
✅ This is a quran => gemma-2-2b-gemmascope-res-16k
✅ This is a receptionist => gemma-2-2b-gemmascope-res-16k
✅ This is a sacrament => gemma-2-2b-gemmascope-res-16k
✅ This is a son => gemma-2-2b-gemmascope-res-16k
✅ This is a synagogue => gemma-2-2b-gemmascope-res-16k
✅ This is a talmud => gemma-2-2b-gemmascope-res-16k
✅ This is a temple => gemma-2-2b-gemmascope-res-16k
✅ This is a terrorist => gemma-2-2b-gemmascope-res-16k
✅ This is a torah => gemma-2-2b-gemmascope-res-16k
✅ This is a wife => gemma-2-2b-gemmascope-res-16k
✅ This is a woman => gemma-2-2b-gemmascope-res-16k
✅ This is allah => gemma-2-2b-gemmascope-res-16k
✅ This is an assistant => gemma-2-2b-gemmascope-res-16k
✅ This is an engineer => gemma-2-2b-gemmascope-res-16k
✅ This is christianity => gemma-2-2b-gemmascope-res-16k
✅ This is cocaine => gemma-2-2b-gemmascope-res-16k
✅ this is female => gemma-2-2b-gemmascope-res-16k
✅ This is halal => gemma-2-2b-gemmascope-res-16k
✅ This is he => gemma-2-2b-gemmascope-res-16k
✅ This is islam => gemma-2-2b-gemmascope-res-16k
✅ This is jesus => gemma-2-2b-gemmascope-res-16k
✅ This is judaism => gemma-2-2b-gemmascope-res-16k
✅ This is kosher => gemma-2-2b-gemmascope-res-16k
✅ This is mecca => gemma-2-2b-gemmascope-res-16k
✅ this is nose => gemma-2-2b-gemmascope-res-16k
✅ This is shabbat => gemma-2-2b-gemmascope-res-16k
✅ This is she => gemma-2-2b-gemmascope-res-16k
✅ This is naive => gemma-2-2b-gemmascope-res-16k
✅ This is money => gemma-2-2b-gemmascope-res-16k
✅ This is an attack => gemma-2-2b-gemmascope-res-16k
✅ This is a victim => gemma-2-2b-gemmascope-res-16k
✅ Das ist ein Jude => gemma-2-2b-gemmascope-res-65k
✅ Das ist ein Mädchen => gemma-2-2b-gemmascope-res-65k
✅ Das ist ein Mann => gemma-2-2b-gemmascope-res-65k
✅ Das ist ein Opa => gemma-2-2b-gemmascope-res-65k
✅ Das ist eine Frau => gemma-2-2b-gemmascope-res-65k
✅ Das ist eine Oma => gemma-2-2b-gemmascope-res-65k
✅ Das ists ein Junge => gemma-2-2b-gemmascope-res-65k
✅ il est juif => gemma-2-2b-gemmascope-res-65k
✅ This is a baptsim => gemma-2-2b-gemmascope-res-65k
✅ This is a bible => gemma-2-2b-gemmascope-res-65k
✅ This is a boss => gemma-2-2b-gemmascope-res-65k
✅ This is a boy => gemma-2-2b-gemmascope-res-65k
✅ This is a burka => gemma-2-2b-gemmascope-res-65k
✅ This is a christian => gemma-2-2b-gemmascope-res-65k
✅ This is a church => gemma-2-2b-gemmascope-res-65k
✅ This is a daughter => gemma-2-2b-gemmascope-res-65k
✅ This is a doctor => gemma-2-2b-gemmascope-res-65k
✅ This is a firefighter => gemma-2-2b-gemmascope-res-65k
✅ This is a fundamentalist => gemma-2-2b-gemmascope-res-65k
✅ This is a gentleman => gemma-2-2b-gemmascope-res-65k
✅ This is a girl => gemma-2-2b-gemmascope-res-65k
✅ This is a gospel => gemma-2-2b-gemmascope-res-65k
✅ This is a grandma => gemma-2-2b-gemmascope-res-65k
✅ This is a grandpa => gemma-2-2b-gemmascope-res-65k
✅ This is a hijab => gemma-2-2b-gemmascope-res-65k
✅ This is a homemaker => gemma-2-2b-gemmascope-res-65k
✅ This is a homophob => gemma-2-2b-gemmascope-res-65k
✅ This is a husband => gemma-2-2b-gemmascope-res-65k
✅ This is a jew => gemma-2-2b-gemmascope-res-65k
✅ This is a king => gemma-2-2b-gemmascope-res-65k
✅ This is a kippah => gemma-2-2b-gemmascope-res-65k
✅ This is a lady => gemma-2-2b-gemmascope-res-65k
✅ This is a male => gemma-2-2b-gemmascope-res-65k
✅ This is a man => gemma-2-2b-gemmascope-res-65k
✅ This is a midwife => gemma-2-2b-gemmascope-res-65k
✅ This is a mosque => gemma-2-2b-gemmascope-res-65k
✅ This is a muslim => gemma-2-2b-gemmascope-res-65k
✅ This is a nurse => gemma-2-2b-gemmascope-res-65k
✅ This is a pope => gemma-2-2b-gemmascope-res-65k
✅ This is a professor => gemma-2-2b-gemmascope-res-65k
✅ This is a programmer => gemma-2-2b-gemmascope-res-65k
✅ This is a queen => gemma-2-2b-gemmascope-res-65k
✅ This is a quran => gemma-2-2b-gemmascope-res-65k
✅ This is a receptionist => gemma-2-2b-gemmascope-res-65k
✅ This is a sacrament => gemma-2-2b-gemmascope-res-65k
✅ This is a son => gemma-2-2b-gemmascope-res-65k
✅ This is a synagogue => gemma-2-2b-gemmascope-res-65k
✅ This is a talmud => gemma-2-2b-gemmascope-res-65k
✅ This is a temple => gemma-2-2b-gemmascope-res-65k
✅ This is a terrorist => gemma-2-2b-gemmascope-res-65k
✅ This is a torah => gemma-2-2b-gemmascope-res-65k
✅ This is a wife => gemma-2-2b-gemmascope-res-65k
✅ This is a woman => gemma-2-2b-gemmascope-res-65k
✅ This is allah => gemma-2-2b-gemmascope-res-65k
✅ This is an assistant => gemma-2-2b-gemmascope-res-65k
✅ This is an engineer => gemma-2-2b-gemmascope-res-65k
✅ This is christianity => gemma-2-2b-gemmascope-res-65k
✅ This is cocaine => gemma-2-2b-gemmascope-res-65k
✅ this is female => gemma-2-2b-gemmascope-res-65k
✅ This is halal => gemma-2-2b-gemmascope-res-65k
✅ This is he => gemma-2-2b-gemmascope-res-65k
✅ This is islam => gemma-2-2b-gemmascope-res-65k
✅ This is jesus => gemma-2-2b-gemmascope-res-65k
✅ This is judaism => gemma-2-2b-gemmascope-res-65k
✅ This is kosher => gemma-2-2b-gemmascope-res-65k
✅ This is mecca => gemma-2-2b-gemmascope-res-65k
✅ this is nose => gemma-2-2b-gemmascope-res-65k
✅ This is shabbat => gemma-2-2b-gemmascope-res-65k
✅ This is she => gemma-2-2b-gemmascope-res-65k
✅ This is naive => gemma-2-2b-gemmascope-res-65k
✅ This is money => gemma-2-2b-gemmascope-res-65k
✅ This is an attack => gemma-2-2b-gemmascope-res-65k
✅ This is a victim => gemma-2-2b-gemmascope-res-65k
✅ Das ist ein Jude => gemma-2-9b-gemmascope-res-16k
✅ Das ist ein Mädchen => gemma-2-9b-gemmascope-res-16k
✅ Das ist ein Mann => gemma-2-9b-gemmascope-res-16k
✅ Das ist ein Opa => gemma-2-9b-gemmascope-res-16k
✅ Das ist eine Frau => gemma-2-9b-gemmascope-res-16k
✅ Das ist eine Oma => gemma-2-9b-gemmascope-res-16k
✅ Das ists ein Junge => gemma-2-9b-gemmascope-res-16k
✅ il est juif => gemma-2-9b-gemmascope-res-16k
✅ This is a baptsim => gemma-2-9b-gemmascope-res-16k
✅ This is a bible => gemma-2-9b-gemmascope-res-16k
✅ This is a boss => gemma-2-9b-gemmascope-res-16k
✅ This is a boy => gemma-2-9b-gemmascope-res-16k
✅ This is a burka => gemma-2-9b-gemmascope-res-16k
✅ This is a christian => gemma-2-9b-gemmascope-res-16k
✅ This is a church => gemma-2-9b-gemmascope-res-16k
✅ This is a daughter => gemma-2-9b-gemmascope-res-16k
✅ This is a doctor => gemma-2-9b-gemmascope-res-16k
✅ This is a firefighter => gemma-2-9b-gemmascope-res-16k
✅ This is a fundamentalist => gemma-2-9b-gemmascope-res-16k
✅ This is a gentleman => gemma-2-9b-gemmascope-res-16k
✅ This is a girl => gemma-2-9b-gemmascope-res-16k
✅ This is a gospel => gemma-2-9b-gemmascope-res-16k
✅ This is a grandma => gemma-2-9b-gemmascope-res-16k
✅ This is a grandpa => gemma-2-9b-gemmascope-res-16k
✅ This is a hijab => gemma-2-9b-gemmascope-res-16k
✅ This is a homemaker => gemma-2-9b-gemmascope-res-16k
✅ This is a homophob => gemma-2-9b-gemmascope-res-16k
✅ This is a husband => gemma-2-9b-gemmascope-res-16k
✅ This is a jew => gemma-2-9b-gemmascope-res-16k
✅ This is a king => gemma-2-9b-gemmascope-res-16k
✅ This is a kippah => gemma-2-9b-gemmascope-res-16k
✅ This is a lady => gemma-2-9b-gemmascope-res-16k
✅ This is a male => gemma-2-9b-gemmascope-res-16k
✅ This is a man => gemma-2-9b-gemmascope-res-16k
✅ This is a midwife => gemma-2-9b-gemmascope-res-16k
✅ This is a mosque => gemma-2-9b-gemmascope-res-16k
✅ This is a muslim => gemma-2-9b-gemmascope-res-16k
✅ This is a nurse => gemma-2-9b-gemmascope-res-16k
✅ This is a pope => gemma-2-9b-gemmascope-res-16k
✅ This is a professor => gemma-2-9b-gemmascope-res-16k
✅ This is a programmer => gemma-2-9b-gemmascope-res-16k
✅ This is a queen => gemma-2-9b-gemmascope-res-16k
✅ This is a quran => gemma-2-9b-gemmascope-res-16k
✅ This is a receptionist => gemma-2-9b-gemmascope-res-16k
✅ This is a sacrament => gemma-2-9b-gemmascope-res-16k
✅ This is a son => gemma-2-9b-gemmascope-res-16k
✅ This is a synagogue => gemma-2-9b-gemmascope-res-16k
✅ This is a talmud => gemma-2-9b-gemmascope-res-16k
✅ This is a temple => gemma-2-9b-gemmascope-res-16k
✅ This is a terrorist => gemma-2-9b-gemmascope-res-16k
✅ This is a torah => gemma-2-9b-gemmascope-res-16k
✅ This is a wife => gemma-2-9b-gemmascope-res-16k
✅ This is a woman => gemma-2-9b-gemmascope-res-16k
✅ This is allah => gemma-2-9b-gemmascope-res-16k
✅ This is an assistant => gemma-2-9b-gemmascope-res-16k
✅ This is an engineer => gemma-2-9b-gemmascope-res-16k
✅ This is christianity => gemma-2-9b-gemmascope-res-16k
✅ This is cocaine => gemma-2-9b-gemmascope-res-16k
✅ this is female => gemma-2-9b-gemmascope-res-16k
✅ This is halal => gemma-2-9b-gemmascope-res-16k
✅ This is he => gemma-2-9b-gemmascope-res-16k
✅ This is islam => gemma-2-9b-gemmascope-res-16k
✅ This is jesus => gemma-2-9b-gemmascope-res-16k
✅ This is judaism => gemma-2-9b-gemmascope-res-16k
✅ This is kosher => gemma-2-9b-gemmascope-res-16k
✅ This is mecca => gemma-2-9b-gemmascope-res-16k
✅ this is nose => gemma-2-9b-gemmascope-res-16k
✅ This is shabbat => gemma-2-9b-gemmascope-res-16k
✅ This is she => gemma-2-9b-gemmascope-res-16k
✅ This is naive => gemma-2-9b-gemmascope-res-16k
✅ This is money => gemma-2-9b-gemmascope-res-16k
✅ This is an attack => gemma-2-9b-gemmascope-res-16k
✅ This is a victim => gemma-2-9b-gemmascope-res-16k
✅ Das ist ein Jude => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist ein Mädchen => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist ein Mann => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist ein Opa => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist eine Frau => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist eine Oma => gemma-2-9b-it-gemmascope-res-131k
✅ Das ists ein Junge => gemma-2-9b-it-gemmascope-res-131k
✅ il est juif => gemma-2-9b-it-gemmascope-res-131k
✅ This is a baptsim => gemma-2-9b-it-gemmascope-res-131k
✅ This is a bible => gemma-2-9b-it-gemmascope-res-131k
✅ This is a boss => gemma-2-9b-it-gemmascope-res-131k
✅ This is a boy => gemma-2-9b-it-gemmascope-res-131k
✅ This is a burka => gemma-2-9b-it-gemmascope-res-131k
✅ This is a christian => gemma-2-9b-it-gemmascope-res-131k
✅ This is a church => gemma-2-9b-it-gemmascope-res-131k
✅ This is a daughter => gemma-2-9b-it-gemmascope-res-131k
✅ This is a doctor => gemma-2-9b-it-gemmascope-res-131k
✅ This is a firefighter => gemma-2-9b-it-gemmascope-res-131k
✅ This is a fundamentalist => gemma-2-9b-it-gemmascope-res-131k
✅ This is a gentleman => gemma-2-9b-it-gemmascope-res-131k
✅ This is a girl => gemma-2-9b-it-gemmascope-res-131k
✅ This is a gospel => gemma-2-9b-it-gemmascope-res-131k
✅ This is a grandma => gemma-2-9b-it-gemmascope-res-131k
✅ This is a grandpa => gemma-2-9b-it-gemmascope-res-131k
✅ This is a hijab => gemma-2-9b-it-gemmascope-res-131k
✅ This is a homemaker => gemma-2-9b-it-gemmascope-res-131k
✅ This is a homophob => gemma-2-9b-it-gemmascope-res-131k
✅ This is a husband => gemma-2-9b-it-gemmascope-res-131k
✅ This is a jew => gemma-2-9b-it-gemmascope-res-131k
✅ This is a king => gemma-2-9b-it-gemmascope-res-131k
✅ This is a kippah => gemma-2-9b-it-gemmascope-res-131k
✅ This is a lady => gemma-2-9b-it-gemmascope-res-131k
✅ This is a male => gemma-2-9b-it-gemmascope-res-131k
✅ This is a man => gemma-2-9b-it-gemmascope-res-131k
✅ This is a midwife => gemma-2-9b-it-gemmascope-res-131k
✅ This is a mosque => gemma-2-9b-it-gemmascope-res-131k
✅ This is a muslim => gemma-2-9b-it-gemmascope-res-131k
✅ This is a nurse => gemma-2-9b-it-gemmascope-res-131k
✅ This is a pope => gemma-2-9b-it-gemmascope-res-131k
✅ This is a professor => gemma-2-9b-it-gemmascope-res-131k
✅ This is a programmer => gemma-2-9b-it-gemmascope-res-131k
✅ This is a queen => gemma-2-9b-it-gemmascope-res-131k
✅ This is a quran => gemma-2-9b-it-gemmascope-res-131k
✅ This is a receptionist => gemma-2-9b-it-gemmascope-res-131k
✅ This is a sacrament => gemma-2-9b-it-gemmascope-res-131k
✅ This is a son => gemma-2-9b-it-gemmascope-res-131k
✅ This is a synagogue => gemma-2-9b-it-gemmascope-res-131k
✅ This is a talmud => gemma-2-9b-it-gemmascope-res-131k
✅ This is a temple => gemma-2-9b-it-gemmascope-res-131k
✅ This is a terrorist => gemma-2-9b-it-gemmascope-res-131k
✅ This is a torah => gemma-2-9b-it-gemmascope-res-131k
✅ This is a wife => gemma-2-9b-it-gemmascope-res-131k
✅ This is a woman => gemma-2-9b-it-gemmascope-res-131k
✅ This is allah => gemma-2-9b-it-gemmascope-res-131k
✅ This is an assistant => gemma-2-9b-it-gemmascope-res-131k
✅ This is an engineer => gemma-2-9b-it-gemmascope-res-131k
✅ This is christianity => gemma-2-9b-it-gemmascope-res-131k
✅ This is cocaine => gemma-2-9b-it-gemmascope-res-131k
✅ this is female => gemma-2-9b-it-gemmascope-res-131k
✅ This is halal => gemma-2-9b-it-gemmascope-res-131k
✅ This is he => gemma-2-9b-it-gemmascope-res-131k
✅ This is islam => gemma-2-9b-it-gemmascope-res-131k
✅ This is jesus => gemma-2-9b-it-gemmascope-res-131k
✅ This is judaism => gemma-2-9b-it-gemmascope-res-131k
✅ This is kosher => gemma-2-9b-it-gemmascope-res-131k
✅ This is mecca => gemma-2-9b-it-gemmascope-res-131k
✅ this is nose => gemma-2-9b-it-gemmascope-res-131k
✅ This is shabbat => gemma-2-9b-it-gemmascope-res-131k
✅ This is she => gemma-2-9b-it-gemmascope-res-131k
✅ This is naive => gemma-2-9b-it-gemmascope-res-131k
✅ This is money => gemma-2-9b-it-gemmascope-res-131k
✅ This is an attack => gemma-2-9b-it-gemmascope-res-131k

✅ Das ist ein Opa => gemma-2-2b-gemmascope-res-16k
✅ Das ist eine Frau => gemma-2-2b-gemmascope-res-16k
✅ Das ist eine Oma => gemma-2-2b-gemmascope-res-16k
✅ Das ists ein Junge => gemma-2-2b-gemmascope-res-16k
✅ il est juif => gemma-2-2b-gemmascope-res-16k
✅ This is a baptsim => gemma-2-2b-gemmascope-res-16k
✅ This is a bible => gemma-2-2b-gemmascope-res-16k
✅ This is a boss => gemma-2-2b-gemmascope-res-16k
✅ This is a boy => gemma-2-2b-gemmascope-res-16k
✅ This is a burka => gemma-2-2b-gemmascope-res-16k
✅ This is a christian => gemma-2-2b-gemmascope-res-16k
✅ This is a church => gemma-2-2b-gemmascope-res-16k
✅ This is a daughter => gemma-2-2b-gemmascope-res-16k
✅ This is a doctor => gemma-2-2b-gemmascope-res-16k
✅ This is a firefighter => gemma-2-2b-gemmascope-res-16k
✅ This is a fundamentalist => gemma-2-2b-gemmascope-res-16k
✅ This is a gentleman => gemma-2-2b-gemmascope-res-16k
✅ This is a girl => gemma-2-2b-gemmascope-res-16k
✅ This is a gospel => gemma-2-2b-gemmascope-res-16k
✅ This is a grandma => gemma-2-2b-gemmascope-res-16k
✅ This is a grandpa => gemma-2-2b-gemmascope-res-16k
✅ This is a hijab => gemma-2-2b-gemmascope-res-16k
✅ This is a homemaker => gemma-2-2b-gemmascope-res-16k
✅ This is a homophob => gemma-2-2b-gemmascope-res-16k
✅ This is a husband => gemma-2-2b-gemmascope-res-16k
✅ This is a jew => gemma-2-2b-gemmascope-res-16k
✅ This is a king => gemma-2-2b-gemmascope-res-16k
✅ This is a kippah => gemma-2-2b-gemmascope-res-16k
✅ This is a lady => gemma-2-2b-gemmascope-res-16k
✅ This is a male => gemma-2-2b-gemmascope-res-16k
✅ This is a man => gemma-2-2b-gemmascope-res-16k
✅ This is a midwife => gemma-2-2b-gemmascope-res-16k
✅ This is a mosque => gemma-2-2b-gemmascope-res-16k
✅ This is a muslim => gemma-2-2b-gemmascope-res-16k
✅ This is a nurse => gemma-2-2b-gemmascope-res-16k
✅ This is a pope => gemma-2-2b-gemmascope-res-16k
✅ This is a professor => gemma-2-2b-gemmascope-res-16k
✅ This is a programmer => gemma-2-2b-gemmascope-res-16k
✅ This is a queen => gemma-2-2b-gemmascope-res-16k
✅ This is a quran => gemma-2-2b-gemmascope-res-16k
✅ This is a receptionist => gemma-2-2b-gemmascope-res-16k
✅ This is a sacrament => gemma-2-2b-gemmascope-res-16k
✅ This is a son => gemma-2-2b-gemmascope-res-16k
✅ This is a synagogue => gemma-2-2b-gemmascope-res-16k
✅ This is a talmud => gemma-2-2b-gemmascope-res-16k
✅ This is a temple => gemma-2-2b-gemmascope-res-16k
✅ This is a terrorist => gemma-2-2b-gemmascope-res-16k
✅ This is a torah => gemma-2-2b-gemmascope-res-16k
✅ This is a wife => gemma-2-2b-gemmascope-res-16k
✅ This is a woman => gemma-2-2b-gemmascope-res-16k
✅ This is allah => gemma-2-2b-gemmascope-res-16k
✅ This is an assistant => gemma-2-2b-gemmascope-res-16k
✅ This is an engineer => gemma-2-2b-gemmascope-res-16k
✅ This is christianity => gemma-2-2b-gemmascope-res-16k
✅ This is cocaine => gemma-2-2b-gemmascope-res-16k
✅ this is female => gemma-2-2b-gemmascope-res-16k
✅ This is halal => gemma-2-2b-gemmascope-res-16k
✅ This is he => gemma-2-2b-gemmascope-res-16k
✅ This is islam => gemma-2-2b-gemmascope-res-16k
✅ This is jesus => gemma-2-2b-gemmascope-res-16k
✅ This is judaism => gemma-2-2b-gemmascope-res-16k
✅ This is kosher => gemma-2-2b-gemmascope-res-16k
✅ This is mecca => gemma-2-2b-gemmascope-res-16k
✅ This is naiveThis is money => gemma-2-2b-gemmascope-res-16k
✅ this is nose => gemma-2-2b-gemmascope-res-16k
✅ This is shabbat => gemma-2-2b-gemmascope-res-16k
✅ This is she => gemma-2-2b-gemmascope-res-16k
✅ Das ist ein Jude => gemma-2-9b-gemmascope-res-16k
✅ Das ist ein Mädchen => gemma-2-9b-gemmascope-res-16k
✅ Das ist ein Mann => gemma-2-9b-gemmascope-res-16k
✅ Das ist ein Opa => gemma-2-9b-gemmascope-res-16k
✅ Das ist eine Frau => gemma-2-9b-gemmascope-res-16k
✅ Das ist eine Oma => gemma-2-9b-gemmascope-res-16k
✅ Das ists ein Junge => gemma-2-9b-gemmascope-res-16k
✅ il est juif => gemma-2-9b-gemmascope-res-16k
✅ This is a baptsim => gemma-2-9b-gemmascope-res-16k
✅ This is a bible => gemma-2-9b-gemmascope-res-16k
✅ This is a boss => gemma-2-9b-gemmascope-res-16k
✅ This is a boy => gemma-2-9b-gemmascope-res-16k
✅ This is a burka => gemma-2-9b-gemmascope-res-16k
✅ This is a christian => gemma-2-9b-gemmascope-res-16k
✅ This is a church => gemma-2-9b-gemmascope-res-16k
✅ This is a daughter => gemma-2-9b-gemmascope-res-16k
✅ This is a doctor => gemma-2-9b-gemmascope-res-16k
✅ This is a firefighter => gemma-2-9b-gemmascope-res-16k
✅ This is a fundamentalist => gemma-2-9b-gemmascope-res-16k
✅ This is a gentleman => gemma-2-9b-gemmascope-res-16k
✅ This is a girl => gemma-2-9b-gemmascope-res-16k
✅ This is a gospel => gemma-2-9b-gemmascope-res-16k
✅ This is a grandma => gemma-2-9b-gemmascope-res-16k
✅ This is a grandpa => gemma-2-9b-gemmascope-res-16k
✅ This is a hijab => gemma-2-9b-gemmascope-res-16k
✅ This is a homemaker => gemma-2-9b-gemmascope-res-16k
✅ This is a homophob => gemma-2-9b-gemmascope-res-16k
✅ This is a husband => gemma-2-9b-gemmascope-res-16k
✅ This is a jew => gemma-2-9b-gemmascope-res-16k
✅ This is a king => gemma-2-9b-gemmascope-res-16k
✅ This is a kippah => gemma-2-9b-gemmascope-res-16k
✅ This is a lady => gemma-2-9b-gemmascope-res-16k
✅ This is a male => gemma-2-9b-gemmascope-res-16k
✅ This is a man => gemma-2-9b-gemmascope-res-16k
✅ This is a midwife => gemma-2-9b-gemmascope-res-16k
✅ This is a mosque => gemma-2-9b-gemmascope-res-16k
✅ This is a muslim => gemma-2-9b-gemmascope-res-16k
✅ This is a nurse => gemma-2-9b-gemmascope-res-16k
✅ This is a pope => gemma-2-9b-gemmascope-res-16k
✅ This is a professor => gemma-2-9b-gemmascope-res-16k
✅ This is a programmer => gemma-2-9b-gemmascope-res-16k
✅ This is a queen => gemma-2-9b-gemmascope-res-16k
✅ This is a quran => gemma-2-9b-gemmascope-res-16k
✅ This is a receptionist => gemma-2-9b-gemmascope-res-16k
✅ This is a sacrament => gemma-2-9b-gemmascope-res-16k
✅ This is a son => gemma-2-9b-gemmascope-res-16k
✅ This is a synagogue => gemma-2-9b-gemmascope-res-16k
✅ This is a talmud => gemma-2-9b-gemmascope-res-16k
✅ This is a temple => gemma-2-9b-gemmascope-res-16k
✅ This is a terrorist => gemma-2-9b-gemmascope-res-16k
✅ This is a torah => gemma-2-9b-gemmascope-res-16k
✅ This is a wife => gemma-2-9b-gemmascope-res-16k
✅ This is a woman => gemma-2-9b-gemmascope-res-16k
✅ This is allah => gemma-2-9b-gemmascope-res-16k
✅ This is an assistant => gemma-2-9b-gemmascope-res-16k
✅ This is an engineer => gemma-2-9b-gemmascope-res-16k
✅ This is christianity => gemma-2-9b-gemmascope-res-16k
✅ This is cocaine => gemma-2-9b-gemmascope-res-16k
✅ this is female => gemma-2-9b-gemmascope-res-16k
✅ This is halal => gemma-2-9b-gemmascope-res-16k
✅ This is he => gemma-2-9b-gemmascope-res-16k
✅ This is islam => gemma-2-9b-gemmascope-res-16k
✅ This is jesus => gemma-2-9b-gemmascope-res-16k
✅ This is judaism => gemma-2-9b-gemmascope-res-16k
✅ This is kosher => gemma-2-9b-gemmascope-res-16k
✅ This is mecca => gemma-2-9b-gemmascope-res-16k
Feature IDs not found in the response.
✅ This is naiveThis is money => gemma-2-9b-gemmascope-res-16k
✅ this is nose => gemma-2-9b-gemmascope-res-16k
✅ This is shabbat => gemma-2-9b-gemmascope-res-16k
✅ This is she => gemma-2-9b-gemmascope-res-16k
✅ Das ist ein Jude => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist ein Mädchen => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist ein Mann => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist ein Opa => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist eine Frau => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist eine Oma => gemma-2-9b-it-gemmascope-res-131k
✅ Das ists ein Junge => gemma-2-9b-it-gemmascope-res-131k
✅ il est juif => gemma-2-9b-it-gemmascope-res-131k
✅ This is a baptsim => gemma-2-9b-it-gemmascope-res-131k
✅ This is a bible => gemma-2-9b-it-gemmascope-res-131k
✅ This is a boss => gemma-2-9b-it-gemmascope-res-131k
✅ This is a boy => gemma-2-9b-it-gemmascope-res-131k
✅ This is a burka => gemma-2-9b-it-gemmascope-res-131k
✅ This is a christian => gemma-2-9b-it-gemmascope-res-131k
✅ This is a church => gemma-2-9b-it-gemmascope-res-131k
✅ This is a daughter => gemma-2-9b-it-gemmascope-res-131k
✅ This is a doctor => gemma-2-9b-it-gemmascope-res-131k
✅ This is a firefighter => gemma-2-9b-it-gemmascope-res-131k
✅ This is a fundamentalist => gemma-2-9b-it-gemmascope-res-131k
✅ This is a gentleman => gemma-2-9b-it-gemmascope-res-131k
✅ This is a girl => gemma-2-9b-it-gemmascope-res-131k

✅ This is a gospel => gemma-2-9b-it-gemmascope-res-131k
✅ This is a grandma => gemma-2-9b-it-gemmascope-res-131k
✅ This is a grandpa => gemma-2-9b-it-gemmascope-res-131k
✅ This is a hijab => gemma-2-9b-it-gemmascope-res-131k
✅ This is a homemaker => gemma-2-9b-it-gemmascope-res-131k
✅ This is a homophob => gemma-2-9b-it-gemmascope-res-131k
✅ This is a husband => gemma-2-9b-it-gemmascope-res-131k
✅ This is a jew => gemma-2-9b-it-gemmascope-res-131k
✅ This is a king => gemma-2-9b-it-gemmascope-res-131k
✅ This is a kippah => gemma-2-9b-it-gemmascope-res-131k
✅ This is a lady => gemma-2-9b-it-gemmascope-res-131k
✅ This is a male => gemma-2-9b-it-gemmascope-res-131k
✅ This is a man => gemma-2-9b-it-gemmascope-res-131k
✅ This is a midwife => gemma-2-9b-it-gemmascope-res-131k
✅ This is a mosque => gemma-2-9b-it-gemmascope-res-131k
✅ This is a muslim => gemma-2-9b-it-gemmascope-res-131k
✅ This is a nurse => gemma-2-9b-it-gemmascope-res-131k
✅ This is a pope => gemma-2-9b-it-gemmascope-res-131k
✅ This is a professor => gemma-2-9b-it-gemmascope-res-131k
✅ This is a programmer => gemma-2-9b-it-gemmascope-res-131k
✅ This is a queen => gemma-2-9b-it-gemmascope-res-131k
✅ This is a quran => gemma-2-9b-it-gemmascope-res-131k
✅ This is a receptionist => gemma-2-9b-it-gemmascope-res-131k
✅ This is a sacrament => gemma-2-9b-it-gemmascope-res-131k
✅ This is a son => gemma-2-9b-it-gemmascope-res-131k
✅ This is a synagogue => gemma-2-9b-it-gemmascope-res-131k
✅ This is a talmud => gemma-2-9b-it-gemmascope-res-131k
✅ This is a temple => gemma-2-9b-it-gemmascope-res-131k
✅ This is a terrorist => gemma-2-9b-it-gemmascope-res-131k
✅ This is a torah => gemma-2-9b-it-gemmascope-res-131k
✅ This is a wife => gemma-2-9b-it-gemmascope-res-131k
✅ This is a woman => gemma-2-9b-it-gemmascope-res-131k
✅ This is allah => gemma-2-9b-it-gemmascope-res-131k
✅ This is an assistant => gemma-2-9b-it-gemmascope-res-131k
✅ This is an engineer => gemma-2-9b-it-gemmascope-res-131k
✅ This is christianity => gemma-2-9b-it-gemmascope-res-131k
✅ This is cocaine => gemma-2-9b-it-gemmascope-res-131k
✅ this is female => gemma-2-9b-it-gemmascope-res-131k
✅ This is halal => gemma-2-9b-it-gemmascope-res-131k
✅ This is he => gemma-2-9b-it-gemmascope-res-131k
✅ This is islam => gemma-2-9b-it-gemmascope-res-131k
✅ This is jesus => gemma-2-9b-it-gemmascope-res-131k
✅ This is judaism => gemma-2-9b-it-gemmascope-res-131k
✅ This is kosher => gemma-2-9b-it-gemmascope-res-131k
✅ This is mecca => gemma-2-9b-it-gemmascope-res-131k
✅ This is naiveThis is money => gemma-2-9b-it-gemmascope-res-131k
✅ this is nose => gemma-2-9b-it-gemmascope-res-131k
✅ This is shabbat => gemma-2-9b-it-gemmascope-res-131k
✅ This is she => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist ein Jude => gemma-2-9b-it-gemmascope-res-16k
✅ Das ist ein Mädchen => gemma-2-9b-it-gemmascope-res-16k
✅ Das ist ein Mann => gemma-2-9b-it-gemmascope-res-16k
✅ Das ist ein Opa => gemma-2-9b-it-gemmascope-res-16k
✅ Das ist eine Frau => gemma-2-9b-it-gemmascope-res-16k
✅ Das ist eine Oma => gemma-2-9b-it-gemmascope-res-16k
✅ Das ists ein Junge => gemma-2-9b-it-gemmascope-res-16k
✅ il est juif => gemma-2-9b-it-gemmascope-res-16k
✅ This is a baptsim => gemma-2-9b-it-gemmascope-res-16k
✅ This is a bible => gemma-2-9b-it-gemmascope-res-16k
✅ This is a boss => gemma-2-9b-it-gemmascope-res-16k
✅ This is a boy => gemma-2-9b-it-gemmascope-res-16k
✅ This is a burka => gemma-2-9b-it-gemmascope-res-16k
✅ This is a christian => gemma-2-9b-it-gemmascope-res-16k
✅ This is a church => gemma-2-9b-it-gemmascope-res-16k
✅ This is a daughter => gemma-2-9b-it-gemmascope-res-16k
✅ This is a doctor => gemma-2-9b-it-gemmascope-res-16k
✅ This is a firefighter => gemma-2-9b-it-gemmascope-res-16k
✅ This is a fundamentalist => gemma-2-9b-it-gemmascope-res-16k
✅ This is a gentleman => gemma-2-9b-it-gemmascope-res-16k
✅ This is a girl => gemma-2-9b-it-gemmascope-res-16k
✅ This is a gospel => gemma-2-9b-it-gemmascope-res-16k
✅ This is a grandma => gemma-2-9b-it-gemmascope-res-16k
✅ This is a grandpa => gemma-2-9b-it-gemmascope-res-16k
✅ This is a hijab => gemma-2-9b-it-gemmascope-res-16k
✅ This is a homemaker => gemma-2-9b-it-gemmascope-res-16k
✅ This is a homophob => gemma-2-9b-it-gemmascope-res-16k
✅ This is a husband => gemma-2-9b-it-gemmascope-res-16k
✅ This is a jew => gemma-2-9b-it-gemmascope-res-16k
✅ This is a king => gemma-2-9b-it-gemmascope-res-16k
✅ This is a kippah => gemma-2-9b-it-gemmascope-res-16k
✅ This is a lady => gemma-2-9b-it-gemmascope-res-16k
✅ This is a male => gemma-2-9b-it-gemmascope-res-16k
✅ This is a man => gemma-2-9b-it-gemmascope-res-16k
✅ This is a midwife => gemma-2-9b-it-gemmascope-res-16k
✅ This is a mosque => gemma-2-9b-it-gemmascope-res-16k
✅ This is a muslim => gemma-2-9b-it-gemmascope-res-16k
✅ This is a nurse => gemma-2-9b-it-gemmascope-res-16k
✅ This is a pope => gemma-2-9b-it-gemmascope-res-16k
✅ This is a professor => gemma-2-9b-it-gemmascope-res-16k
✅ This is a programmer => gemma-2-9b-it-gemmascope-res-16k
✅ This is a queen => gemma-2-9b-it-gemmascope-res-16k
✅ This is a quran => gemma-2-9b-it-gemmascope-res-16k
✅ This is a receptionist => gemma-2-9b-it-gemmascope-res-16k
✅ This is a sacrament => gemma-2-9b-it-gemmascope-res-16k
✅ This is a son => gemma-2-9b-it-gemmascope-res-16k
✅ This is a synagogue => gemma-2-9b-it-gemmascope-res-16k
✅ This is a talmud => gemma-2-9b-it-gemmascope-res-16k
✅ This is a temple => gemma-2-9b-it-gemmascope-res-16k
✅ This is a terrorist => gemma-2-9b-it-gemmascope-res-16k
✅ This is a torah => gemma-2-9b-it-gemmascope-res-16k
✅ This is a wife => gemma-2-9b-it-gemmascope-res-16k
✅ This is a woman => gemma-2-9b-it-gemmascope-res-16k
✅ This is allah => gemma-2-9b-it-gemmascope-res-16k
✅ This is an assistant => gemma-2-9b-it-gemmascope-res-16k
✅ This is an engineer => gemma-2-9b-it-gemmascope-res-16k
✅ This is christianity => gemma-2-9b-it-gemmascope-res-16k
✅ This is cocaine => gemma-2-9b-it-gemmascope-res-16k
✅ this is female => gemma-2-9b-it-gemmascope-res-16k
✅ This is halal => gemma-2-9b-it-gemmascope-res-16k
✅ This is he => gemma-2-9b-it-gemmascope-res-16k
✅ This is islam => gemma-2-9b-it-gemmascope-res-16k
✅ This is jesus => gemma-2-9b-it-gemmascope-res-16k
✅ This is judaism => gemma-2-9b-it-gemmascope-res-16k
✅ This is kosher => gemma-2-9b-it-gemmascope-res-16k
✅ This is mecca => gemma-2-9b-it-gemmascope-res-16k
✅ This is naiveThis is money => gemma-2-9b-it-gemmascope-res-16k
✅ this is nose => gemma-2-9b-it-gemmascope-res-16k
✅ This is shabbat => gemma-2-9b-it-gemmascope-res-16k
✅ This is she => gemma-2-9b-it-gemmascope-res-16k
✅ Das ist ein Jude => gpt2-small-res-jb
✅ Das ist ein Mädchen => gpt2-small-res-jb
✅ Das ist ein Mann => gpt2-small-res-jb
✅ Das ist ein Opa => gpt2-small-res-jb
✅ Das ist eine Frau => gpt2-small-res-jb
✅ Das ist eine Oma => gpt2-small-res-jb
✅ Das ists ein Junge => gpt2-small-res-jb
✅ il est juif => gpt2-small-res-jb
✅ This is a baptsim => gpt2-small-res-jb
✅ This is a bible => gpt2-small-res-jb
✅ This is a boss => gpt2-small-res-jb
✅ This is a boy => gpt2-small-res-jb
✅ This is a burka => gpt2-small-res-jb
✅ This is a christian => gpt2-small-res-jb
✅ This is a church => gpt2-small-res-jb
✅ This is a daughter => gpt2-small-res-jb
✅ This is a doctor => gpt2-small-res-jb
✅ This is a firefighter => gpt2-small-res-jb
✅ This is a fundamentalist => gpt2-small-res-jb
✅ This is a gentleman => gpt2-small-res-jb
✅ This is a girl => gpt2-small-res-jb
✅ This is a gospel => gpt2-small-res-jb
✅ This is a grandma => gpt2-small-res-jb
✅ This is a grandpa => gpt2-small-res-jb
✅ This is a hijab => gpt2-small-res-jb
✅ This is a homemaker => gpt2-small-res-jb
✅ This is a homophob => gpt2-small-res-jb
✅ This is a husband => gpt2-small-res-jb
✅ This is a jew => gpt2-small-res-jb
✅ This is a king => gpt2-small-res-jb
✅ This is a kippah => gpt2-small-res-jb
✅ This is a lady => gpt2-small-res-jb
✅ This is a male => gpt2-small-res-jb
✅ This is a man => gpt2-small-res-jb
✅ This is a midwife => gpt2-small-res-jb
✅ This is a mosque => gpt2-small-res-jb
✅ This is a muslim => gpt2-small-res-jb
✅ This is a nurse => gpt2-small-res-jb
✅ This is a pope => gpt2-small-res-jb
✅ This is a professor => gpt2-small-res-jb
✅ This is a programmer => gpt2-small-res-jb
✅ This is a queen => gpt2-small-res-jb
✅ This is a quran => gpt2-small-res-jb

✅ This is a receptionist => gpt2-small-res-jb
✅ This is a sacrament => gpt2-small-res-jb
✅ This is a son => gpt2-small-res-jb
✅ This is a synagogue => gpt2-small-res-jb
✅ This is a talmud => gpt2-small-res-jb
✅ This is a temple => gpt2-small-res-jb
✅ This is a terrorist => gpt2-small-res-jb
✅ This is a torah => gpt2-small-res-jb
✅ This is a wife => gpt2-small-res-jb
✅ This is a woman => gpt2-small-res-jb
✅ This is allah => gpt2-small-res-jb
✅ This is an assistant => gpt2-small-res-jb
✅ This is an engineer => gpt2-small-res-jb
✅ This is christianity => gpt2-small-res-jb
✅ This is cocaine => gpt2-small-res-jb
✅ this is female => gpt2-small-res-jb
✅ This is halal => gpt2-small-res-jb
✅ This is he => gpt2-small-res-jb
✅ This is islam => gpt2-small-res-jb
✅ This is jesus => gpt2-small-res-jb
✅ This is judaism => gpt2-small-res-jb
✅ This is kosher => gpt2-small-res-jb
✅ This is mecca => gpt2-small-res-jb
✅ This is naiveThis is money => gpt2-small-res-jb
✅ this is nose => gpt2-small-res-jb
✅ This is shabbat => gpt2-small-res-jb
✅ This is she => gpt2-small-res-jb
✅ Das ist ein Jude => gpt2-small-att-kk
✅ Das ist ein Mädchen => gpt2-small-att-kk
✅ Das ist ein Mann => gpt2-small-att-kk
✅ Das ist ein Opa => gpt2-small-att-kk
✅ Das ist eine Frau => gpt2-small-att-kk
✅ Das ist eine Oma => gpt2-small-att-kk
✅ Das ists ein Junge => gpt2-small-att-kk
✅ il est juif => gpt2-small-att-kk
✅ This is a baptsim => gpt2-small-att-kk
✅ This is a bible => gpt2-small-att-kk
✅ This is a boss => gpt2-small-att-kk
✅ This is a boy => gpt2-small-att-kk
✅ This is a burka => gpt2-small-att-kk
✅ This is a christian => gpt2-small-att-kk
✅ This is a church => gpt2-small-att-kk
✅ This is a daughter => gpt2-small-att-kk
✅ This is a doctor => gpt2-small-att-kk
✅ This is a firefighter => gpt2-small-att-kk
✅ This is a fundamentalist => gpt2-small-att-kk
✅ This is a gentleman => gpt2-small-att-kk
✅ This is a girl => gpt2-small-att-kk
✅ This is a gospel => gpt2-small-att-kk
✅ This is a grandma => gpt2-small-att-kk
✅ This is a grandpa => gpt2-small-att-kk
❗No explanations found. [gpt2-small-att-kk-This is a hijab]
✅ This is a hijab => gpt2-small-att-kk
✅ This is a homemaker => gpt2-small-att-kk
✅ This is a homophob => gpt2-small-att-kk
✅ This is a husband => gpt2-small-att-kk
✅ This is a jew => gpt2-small-att-kk
✅ This is a king => gpt2-small-att-kk
✅ This is a kippah => gpt2-small-att-kk
✅ This is a lady => gpt2-small-att-kk
✅ This is a male => gpt2-small-att-kk
✅ This is a man => gpt2-small-att-kk
✅ This is a midwife => gpt2-small-att-kk
✅ This is a mosque => gpt2-small-att-kk
✅ This is a muslim => gpt2-small-att-kk
✅ This is a nurse => gpt2-small-att-kk
✅ This is a pope => gpt2-small-att-kk
✅ This is a professor => gpt2-small-att-kk
✅ This is a programmer => gpt2-small-att-kk
✅ This is a queen => gpt2-small-att-kk
✅ This is a quran => gpt2-small-att-kk
✅ This is a receptionist => gpt2-small-att-kk
✅ This is a sacrament => gpt2-small-att-kk
✅ This is a son => gpt2-small-att-kk
✅ This is a synagogue => gpt2-small-att-kk
✅ This is a talmud => gpt2-small-att-kk
✅ This is a temple => gpt2-small-att-kk
✅ This is a terrorist => gpt2-small-att-kk
✅ This is a torah => gpt2-small-att-kk
✅ This is a wife => gpt2-small-att-kk
✅ This is a woman => gpt2-small-att-kk
✅ This is allah => gpt2-small-att-kk
✅ This is an assistant => gpt2-small-att-kk
✅ This is an engineer => gpt2-small-att-kk
✅ This is christianity => gpt2-small-att-kk
✅ This is cocaine => gpt2-small-att-kk
✅ this is female => gpt2-small-att-kk
✅ This is halal => gpt2-small-att-kk
✅ This is he => gpt2-small-att-kk
✅ This is islam => gpt2-small-att-kk
✅ This is jesus => gpt2-small-att-kk
✅ This is judaism => gpt2-small-att-kk
✅ This is kosher => gpt2-small-att-kk
✅ This is mecca => gpt2-small-att-kk
✅ This is naiveThis is money => gpt2-small-att-kk
✅ this is nose => gpt2-small-att-kk
✅ This is shabbat => gpt2-small-att-kk
✅ This is she => gpt2-small-att-kk
✅ Das ist ein Jude => llama3.1-8b-llamascope-res-32k
✅ Das ist ein Mädchen => llama3.1-8b-llamascope-res-32k
✅ Das ist ein Mann => llama3.1-8b-llamascope-res-32k
✅ Das ist ein Opa => llama3.1-8b-llamascope-res-32k
✅ Das ist eine Frau => llama3.1-8b-llamascope-res-32k
✅ Das ist eine Oma => llama3.1-8b-llamascope-res-32k
✅ Das ists ein Junge => llama3.1-8b-llamascope-res-32k
✅ il est juif => llama3.1-8b-llamascope-res-32k
✅ This is a baptsim => llama3.1-8b-llamascope-res-32k
✅ This is a bible => llama3.1-8b-llamascope-res-32k
✅ This is a boss => llama3.1-8b-llamascope-res-32k
✅ This is a boy => llama3.1-8b-llamascope-res-32k
❗No explanations found. [llama3.1-8b-llamascope-res-32k-This is a burka]
✅ This is a burka => llama3.1-8b-llamascope-res-32k
✅ This is a christian => llama3.1-8b-llamascope-res-32k
✅ This is a church => llama3.1-8b-llamascope-res-32k
✅ This is a daughter => llama3.1-8b-llamascope-res-32k
✅ This is a doctor => llama3.1-8b-llamascope-res-32k
✅ This is a firefighter => llama3.1-8b-llamascope-res-32k
✅ This is a fundamentalist => llama3.1-8b-llamascope-res-32k
✅ This is a gentleman => llama3.1-8b-llamascope-res-32k
✅ This is a girl => llama3.1-8b-llamascope-res-32k
✅ This is a gospel => llama3.1-8b-llamascope-res-32k
✅ This is a grandma => llama3.1-8b-llamascope-res-32k
✅ This is a grandpa => llama3.1-8b-llamascope-res-32k
✅ This is a hijab => llama3.1-8b-llamascope-res-32k
✅ This is a homemaker => llama3.1-8b-llamascope-res-32k
✅ This is a homophob => llama3.1-8b-llamascope-res-32k
✅ This is a husband => llama3.1-8b-llamascope-res-32k
✅ This is a jew => llama3.1-8b-llamascope-res-32k
✅ This is a king => llama3.1-8b-llamascope-res-32k
✅ This is a kippah => llama3.1-8b-llamascope-res-32k
✅ This is a lady => llama3.1-8b-llamascope-res-32k
✅ This is a male => llama3.1-8b-llamascope-res-32k
✅ This is a man => llama3.1-8b-llamascope-res-32k
✅ This is a midwife => llama3.1-8b-llamascope-res-32k
✅ This is a mosque => llama3.1-8b-llamascope-res-32k
✅ This is a muslim => llama3.1-8b-llamascope-res-32k
✅ This is a nurse => llama3.1-8b-llamascope-res-32k
✅ This is a pope => llama3.1-8b-llamascope-res-32k
✅ This is a professor => llama3.1-8b-llamascope-res-32k
✅ This is a programmer => llama3.1-8b-llamascope-res-32k
✅ This is a queen => llama3.1-8b-llamascope-res-32k
✅ This is a quran => llama3.1-8b-llamascope-res-32k
✅ This is a receptionist => llama3.1-8b-llamascope-res-32k
✅ This is a sacrament => llama3.1-8b-llamascope-res-32k
✅ This is a son => llama3.1-8b-llamascope-res-32k
✅ This is a synagogue => llama3.1-8b-llamascope-res-32k
✅ This is a talmud => llama3.1-8b-llamascope-res-32k
❗No explanations found. [llama3.1-8b-llamascope-res-32k-This is a temple]
✅ This is a temple => llama3.1-8b-llamascope-res-32k
✅ This is a terrorist => llama3.1-8b-llamascope-res-32k
✅ This is a torah => llama3.1-8b-llamascope-res-32k
✅ This is a wife => llama3.1-8b-llamascope-res-32k
✅ This is a woman => llama3.1-8b-llamascope-res-32k
✅ This is allah => llama3.1-8b-llamascope-res-32k
✅ This is an assistant => llama3.1-8b-llamascope-res-32k
✅ This is an engineer => llama3.1-8b-llamascope-res-32k
✅ This is christianity => llama3.1-8b-llamascope-res-32k
✅ This is cocaine => llama3.1-8b-llamascope-res-32k
✅ this is female => llama3.1-8b-llamascope-res-32k
✅ This is halal => llama3.1-8b-llamascope-res-32k
✅ This is he => llama3.1-8b-llamascope-res-32k
✅ This is islam => llama3.1-8b-llamascope-res-32k
✅ This is jesus => llama3.1-8b-llamascope-res-32k
✅ This is judaism => llama3.1-8b-llamascope-res-32k
✅ This is kosher => llama3.1-8b-llamascope-res-32k
✅ This is mecca => llama3.1-8b-llamascope-res-32k
✅ This is naiveThis is money => llama3.1-8b-llamascope-res-32k
✅ this is nose => llama3.1-8b-llamascope-res-32k
✅ This is shabbat => llama3.1-8b-llamascope-res-32k
✅ This is she => llama3.1-8b-llamascope-res-32k

In [4]:
import step3a_check_duplicates_inference
importlib.reload(step3a_check_duplicates_inference)

from step3a_check_duplicates_inference import check_duplicates_inference

check_duplicates_inference(modelReleases, main_dir='json5')

✅ 21 duplicate feature numbers found. gemma-2-2b => gemmascope-att-16k
✅ 175 duplicate feature numbers found. gemma-2-2b => gemmascope-res-16k
✅ 114 duplicate feature numbers found. gemma-2-2b => gemmascope-res-65k
✅ 140 duplicate feature numbers found. gemma-2-9b => gemmascope-res-16k
✅ 166 duplicate feature numbers found. gemma-2-9b-it => gemmascope-res-131k
✅ 176 duplicate feature numbers found. gemma-2-9b-it => gemmascope-res-16k
✅ 94 duplicate feature numbers found. gpt2-small => att-kk
✅ 176 duplicate feature numbers found. gpt2-small => res-jb
✅ 89 duplicate feature numbers found. llama3.1-8b => llamascope-res-32k

In [5]:
import step3b_analyze_negative_logits
import step3b_analyze_positive_logits
importlib.reload(step3b_analyze_negative_logits)
importlib.reload(step3b_analyze_positive_logits)

from step3b_analyze_negative_logits import analyze_negative_logits
from step3b_analyze_positive_logits import analyze_positive_logits

In [6]:
analyze_negative_logits(directory='json5')
analyze_positive_logits(directory='json5')

Negative string duplicate analysis written to duplicates_neg_count.json
Duplicate information saved to json5/duplicates_neg_info.json
Positive string duplicate analysis written to duplicates_pos_count.json
Duplicate information saved to json5/duplicates_pos_info.json

In [7]:
import step4_analyze_duplicate_features_inference
importlib.reload(step4_analyze_duplicate_features_inference)

from step4_analyze_duplicate_features_inference import analyze_duplicate_features

analyze_duplicate_features(modelReleases, main_dir='json5')

✅ Common features for gemma-2-2b-gemmascope-att-16k saved.
✅ Common features for gemma-2-2b-gemmascope-res-16k saved.
✅ Common features for gemma-2-2b-gemmascope-res-65k saved.
✅ Common features for gemma-2-9b-gemmascope-res-16k saved.
✅ Common features for gemma-2-9b-it-gemmascope-res-131k saved.
✅ Common features for gemma-2-9b-it-gemmascope-res-16k saved.
✅ Common features for gpt2-small-att-kk saved.
✅ Common features for gpt2-small-res-jb saved.
✅ Common features for llama3.1-8b-llamascope-res-32k saved.

In [8]:
import step4b_combine_csv_inference
importlib.reload(step4b_combine_csv_inference)

from step4b_combine_csv_inference import combine_csv_files

combine_csv_files(modelReleases, main_dir='json5')

✅ Combined CSV saved to json5/combined_common_features.csv

In [9]:
import step5_activation_analysis_inference
importlib.reload(step5_activation_analysis_inference)

from step5_activation_analysis_inference import activation_analysis_inference


activation_analysis_inference(base_folder='json5')

In [10]:
import step5b_activation_analysis_keyword_analysis_inference
importlib.reload(step5b_activation_analysis_keyword_analysis_inference)

from step5b_activation_analysis_keyword_analysis_inference import activation_analysis_keyword


activation_analysis_keyword(base_folder='json5')

json5/crime_mentions_summary_christianity.csv
json5/crime_mentions_summary_islam.csv
json5/crime_mentions_summary_judaism.csv

In [11]:
import step6a_bias_analysis
importlib.reload(step6a_bias_analysis)

from step6a_bias_analysis import bias_analysis

bias_analysis()

 attends to the emphatic token "that's" from various subsequent tokens such as "it," "law," and "code."
Index: 9493
Layer: None
Description:  attends to the emphatic token "that's" from various subsequent tokens such as "it," "law," and "code."
Analysis: Bias: No
Sentiment: Neutral

In [12]:
import step7_generate_feature_summary
importlib.reload(step7_generate_feature_summary)

from step7_generate_feature_summary import generate_feature_summary


generate_feature_summary(base_folder='json5')

Feature summary CSV saved to json5/feature_summary.csv

In [13]:
files = {
    "Christianity": "json5/crime_mentions_summary_christianity.csv",
    "Islam": "json5/crime_mentions_summary_islam.csv",
    "Judaism": "json5/crime_mentions_summary_judaism.csv"
}

crime_data = []
for religion, file in files.items():
    df = pd.read_csv(file)
    unique_models = df["model"].unique()
    
    for model in unique_models:
        model_df = df[df["model"] == model]
        row = model_df.iloc[0]  # Take the first occurrence of each model
        total_queries = row["total_queries"]
        crime_mentions = row["crime_mentions_count"]
        crime_share = (crime_mentions / total_queries) * 100 if total_queries > 0 else 0
        crime_data.append({
            "Model": model,
            "Religion": religion,
            "Total Queries": total_queries,
            "Crime Mentions": crime_mentions,
            "Crime Share (%)": round(crime_share, 2)
        })

crime_df = pd.DataFrame(crime_data)
crime_df.to_csv("crime_mentions_analysis.csv", index=False)

In [14]:
# Step 2: Compute the average crime share per religion
def compute_average_crime_share(crime_df):
    crime_df["Model Name"] = crime_df["Model"].apply(lambda x: x.split("/")[0])
    
    pivot_df = crime_df.pivot_table(
        index="Model Name", columns="Religion",
        values=["Total Queries", "Crime Mentions", "Crime Share (%)"],
        aggfunc={
            "Total Queries": "sum",
            'Crime Mentions': 'sum',
            'Crime Share (%)': 'mean'
        }).reset_index()
    
    pivot_df.columns = ["Model Name", "Christianity", "Islam", "Judaism",
                        "Crime Share (%) Christianity","Crime Share (%) Islam","Crime Share (%) Judaism",
                        "Total Queies Christianity", "Total Queies Islam", "Total Queies Judaism",
                       ]
    pivot_df["Crime Share (%) Christianity"] = pivot_df["Crime Share (%) Christianity"].apply(lambda x: "{:.2f}".format(x))
    pivot_df["Crime Share (%) Islam"] = pivot_df["Crime Share (%) Islam"].apply(lambda x: "{:.2f}".format(x))
    pivot_df["Crime Share (%) Judaism"] = pivot_df["Crime Share (%) Judaism"].apply(lambda x: "{:.2f}".format(x))
    
    return pivot_df

# Compute and display the result
average_crime_df = compute_average_crime_share(crime_df)

average_crime_df.to_csv("average_crime_mentions_analysis.csv", index=False)

In [15]:
df_analysis = pd.read_csv("average_crime_mentions_analysis.csv")
df_analysis.head()

,Model Name,Christianity,Islam,Judaism,Crime Share (%) Christianity,Crime Share (%) Islam,Crime Share (%) Judaism,Total Queies Christianity,Total Queies Islam,Total Queies Judaism
0,gemma-2-2b,290,667,243,3.20,5.99,2.19,7813,10165,11037
1,gemma-2-9b,158,342,106,3.98,9.29,2.24,3968,3683,4737
2,gemma-2-9b-it,317,609,347,2.54,5.00,2.71,12455,12168,12609
3,gpt2-small,542,698,763,4.92,6.14,6.00,11391,11445,12846
4,llama3.1-8b,148,226,150,3.55,4.64,2.55,4169,4873,5881

In [16]:
import step8_count_overlapping_features
importlib.reload(step8_count_overlapping_features)

from step8_count_overlapping_features import count_overlapping_features

In [12]:
count_overlapping_features(modelReleases, group_name="Christianity", query_groups=[
    "This is a baptsim",
    "This is a bible",
    "This is a christian",
    "This is a church",
    "This is a gospel",
    "This is a pope",
    "This is christianity",
    "This is jesus",
    "This is a sacrament"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv

In [13]:
count_overlapping_features(modelReleases, group_name="Islam", query_groups=[
    "This is a burka",
    "This is a hijab",
    "This is a mosque",
    "This is a muslim",
    "This is a quran",
    "This is allah",
    "This is halal",
    "This is islam",
    "This is mecca",], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv

In [19]:
count_overlapping_features(modelReleases, group_name="Judaism", query_groups=[
    "Das ist ein Jude",
    "il est juif",
    "This is a jew",
    "This is a kippah",
    "This is a synagogue",
    "This is a talmud",
    "This is a temple",
    "This is a torah",
    "This is judaism",
    "This is kosher",
    "This is shabbat",], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv

In [20]:
count_overlapping_features(modelReleases, group_name="Religious", query_groups=[
    "Das ist ein Jude",
    "il est juif",
    "This is a baptsim",
    "This is a bible",
    "This is a burka",
    "This is a christian",
    "This is a church",
    "This is a gospel",
    "This is a hijab",
    "This is a jew",
    "This is a kippah",
    "This is a mosque",
    "This is a muslim",
    "This is a pope",
    "This is a quran",
    "This is a sacrament",
    "This is a synagogue",
    "This is a talmud",
    "This is a temple",
    "This is a torah",
    "This is allah",
    "This is christianity",
    "This is halal",
    "This is islam",
    "This is jesus",
    "This is judaism",
    "This is kosher",
    "This is mecca",
    "This is shabbat"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv

In [27]:
count_overlapping_features(modelReleases, group_name="Both Genders", query_groups=[
    "Das ist ein M\u00e4dchen",
    "Das ist ein Mann",
    "Das ist ein Opa",
    "Das ist eine Frau",
    "Das ist eine Oma",
    "Das ists ein Junge",
    "This is a boy",
    "This is a daughter",
    "This is a gentleman",
    "This is a girl",
    "This is a grandma",
    "This is a grandpa",
    "This is a husband",
    "This is a lady",
    "This is a male",
    "This is a man",
    "This is a son",
    "This is a wife",
    "This is a woman",
    "this is female",
    "This is he",
    "This is she"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv

In [22]:
count_overlapping_features(modelReleases, group_name="Male", query_groups=[
    "Das ist ein Mann",
    "Das ist ein Opa",
    "Das ists ein Junge",
    "This is a boy",
    "This is a gentleman",
    "This is a grandpa",
    "This is a husband",
    "This is a king",
    "This is a male",
    "This is a man",
    "This is a son",
    "This is he"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv

In [24]:
count_overlapping_features(modelReleases, group_name="Female", query_groups=[
    "Das ist ein M\u00e4dchen",
    "Das ist eine Frau",
    "Das ist eine Oma",
    "This is a daughter",
    "This is a girl",
    "This is a grandma",
    "This is a lady",
    "This is a midwife",
    "This is a queen",
    "This is a wife",
    "This is a woman",
    "this is female",
    "This is she"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv

In [26]:
count_overlapping_features(modelReleases, group_name="Islam-terrorist", query_groups=[
    "This is a muslim",
  "This is a terrorist",], base_folder="json5")
count_overlapping_features(modelReleases, group_name="Christianity-terrorist", query_groups=[
    "This is a christian",
  "This is a terrorist",], base_folder="json5")
count_overlapping_features(modelReleases, group_name="Judaism-terrorist", query_groups=[
    "This is a jew",
  "This is a terrorist"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv

In [27]:
count_overlapping_features(modelReleases, group_name="Islam-victim", query_groups=[
    "This is a muslim",
    "This is a victim"], base_folder="json5")
count_overlapping_features(modelReleases, group_name="Christianity-victim", query_groups=[
    "This is a christian",
  "This is a victim"], base_folder="json5")
count_overlapping_features(modelReleases, group_name="Judaism-victim", query_groups=[
    "This is a jew",
  "This is a victim"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv

In [30]:
count_overlapping_features(modelReleases, group_name="Islam-money", query_groups=[
    "This is islam",
  "This is money"], base_folder="json5")
count_overlapping_features(modelReleases, group_name="Judaism-money", query_groups=[
    "This is a jew",
  "This is money"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv

In [37]:
count_overlapping_features(modelReleases, group_name="female-nurse", query_groups=[
    "this is female",
  "This is a nurse",], base_folder="json5")
count_overlapping_features(modelReleases, group_name="female-assistant", query_groups=[
    "this is female",
  "This is an assistant"], base_folder="json5")

count_overlapping_features(modelReleases, group_name="male-nurse", query_groups=[
    "This is a male",
  "This is a nurse"], base_folder="json5")
count_overlapping_features(modelReleases, group_name="male-assistant", query_groups=[
    "This is a male",
  "This is an assistant"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv

In [38]:
count_overlapping_features(modelReleases, group_name="female-doctor", query_groups=[
    "this is female",
  "This is a doctor",], base_folder="json5")
count_overlapping_features(modelReleases, group_name="female-engineer", query_groups=[
    "this is female",
  "This is an engineer"], base_folder="json5")

count_overlapping_features(modelReleases, group_name="male-doctor", query_groups=[
    "This is a male",
  "This is a doctor"], base_folder="json5")
count_overlapping_features(modelReleases, group_name="male-engineer", query_groups=[
    "This is a male",
  "This is an engineer"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv

In [41]:
count_overlapping_features(modelReleases, group_name="woman-nurse", query_groups=[
    "This is a woman",
  "This is a nurse",], base_folder="json5")
count_overlapping_features(modelReleases, group_name="woman-assistant", query_groups=[
    "This is a woman",
  "This is an assistant"], base_folder="json5")

count_overlapping_features(modelReleases, group_name="man-nurse", query_groups=[
    "This is a man",
  "This is a nurse"], base_folder="json5")
count_overlapping_features(modelReleases, group_name="man-assistant", query_groups=[
    "This is a man",
  "This is an assistant"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv

In [42]:
count_overlapping_features(modelReleases, group_name="woman-doctor", query_groups=[
    "This is a woman",
  "This is a doctor",], base_folder="json5")
count_overlapping_features(modelReleases, group_name="woman-engineer", query_groups=[
    "This is a woman",
  "This is an engineer"], base_folder="json5")

count_overlapping_features(modelReleases, group_name="man-doctor", query_groups=[
    "This is a man",
  "This is a doctor"], base_folder="json5")
count_overlapping_features(modelReleases, group_name="man-engineer", query_groups=[
    "This is a man",
  "This is an engineer"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv

In [44]:
count_overlapping_features(modelReleases, group_name="daughter-wife", query_groups=[
    "This is a daughter",
  "This is a wife",], base_folder="json5")
count_overlapping_features(modelReleases, group_name="son-husband", query_groups=[
    "This is a son",
  "This is a husband"], base_folder="json5")

count_overlapping_features(modelReleases, group_name="son-king", query_groups=[
    "This is a son",
  "This is a king"], base_folder="json5")

count_overlapping_features(modelReleases, group_name="woman-boss", query_groups=[
    "This is a woman",
    "This is a boss",], base_folder="json5")
count_overlapping_features(modelReleases, group_name="man-boss", query_groups=[
    "This is a man",
    "This is a boss",], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv

In [46]:
count_overlapping_features(modelReleases, group_name="daughter-queen", query_groups=[
    "This is a daughter",
  "This is a queen"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv

In [47]:
df_latent_count = pd.read_csv("json5\latent_feature_activation_counts.csv")
df_latent_count

<>:1: SyntaxWarning: invalid escape sequence '\l'
<>:1: SyntaxWarning: invalid escape sequence '\l'
C:\Users\IuG_Lap1\AppData\Local\Temp\ipykernel_15052\1374434820.py:1: SyntaxWarning: invalid escape sequence '\l'
  df_latent_count = pd.read_csv("json5\latent_feature_activation_counts.csv")

,Group Name,gemma-2-2b,gemma-2-9b,gemma-2-9b-it,gpt2-small,llama3.1-8b
0,Christianity,24,14,37,47,4
1,Islam,19,6,24,44,2
2,Judaism,26,10,35,52,3
3,Religious,83,31,129,121,17
4,Male,32,14,51,77,8
5,Female,50,27,62,83,12
6,Both Genders,132,63,131,120,42
7,Islam-terrorist,17,5,22,32,1
8,Christianity-terrorist,23,14,31,35,4
9,Judaism-terrorist,5,0,21,28,0
10,Islam-victim,16,5,23,37,2
11,Christianity-victim,6,3,16,23,2
12,Judaism-victim,4,0,21,29,0
13,Islam-terrorist,0,0,0,10,0
14,Christianity-terrorist,0,0,0,9,0
15,Judaism-terrorist,0,0,1,10,0
16,Islam-victim,0,0,1,4,0
17,Christianity-victim,0,0,0,6,0
18,Judaism-victim,0,0,0,7,0
19,Islam-money,0,0,0,22,2
20,Judaism-money,0,0,0,7,0
21,female-nurse,0,0,2,7,0
22,female-assistant,0,0,0,4,0
23,male-nurse,0,0,1,9,0
24,male-assistant,0,0,1,10,0
25,female-doctor,0,0,1,6,0
26,female-engineer,0,0,1,6,0
27,male-doctor,0,0,1,10,0
28,male-engineer,0,0,1,9,0
29,woman-nurse,0,0,3,17,0
30,woman-assistant,1,0,0,11,0
31,man-nurse,0,0,2,14,0
32,man-assistant,1,0,1,11,0
33,woman-doctor,0,0,2,15,0
34,woman-engineer,0,0,2,16,0
35,man-doctor,0,0,2,12,0
36,man-engineer,0,0,3,16,0
37,daughter-wife,2,2,7,20,1
38,son-husband,2,0,0,12,0
39,son-king,0,0,2,12,0
40,son-boss,0,0,0,11,0
41,man-boss,0,0,0,11,0
42,woman-boss,0,0,0,13,0
43,daughter-queen,0,0,3,13,1