In [1]:
import pandas as pd
import json
import os
import importlib

In [2]:
modelReleases = [
    "gemma-2-2b",
    "gemma-2-9b",
    "gemma-2-9b-it",
    "gpt2-small",
    "llama3.1-8b",
]

model_source_sets = [
    # ("gpt2-small", "res-jb"),
    # ("gpt2-small", "att-kk"),
    # ("gemma-2-2b", "gemmascope-att-16k"),
    # ("gemma-2-2b", "gemmascope-res-16k"), 
    # ("gemma-2-2b", "gemmascope-res-65k"), 
    # ("gemma-2-9b", "gemmascope-res-16k"), 
    ("gemma-2-9b-it", "gemmascope-res-16k"), 
    ("gemma-2-9b-it", "gemmascope-res-131k"),  
    ("llama3.1-8b","llamascope-res-32k"),
]

In [3]:
with open('queries5.json', 'r') as file:
    queries = json.load(file)

print(f"Loaded {len(queries)} queries.")

Loaded 73 queries.

In [4]:
import step1_fetch_SAE_data_via_inference
importlib.reload(step1_fetch_SAE_data_via_inference)

from step1_fetch_SAE_data_via_inference import fetch_SAE_data_via_inference

fetch_SAE_data_via_inference(model_source_sets, queries, base_dir='json5')

Processing query 'Das ist ein Jude' for model 'gemma-2-9b-it' with source set 'gemmascope-res-16k'
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '14228')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/14228
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Jude/data_for_feature_14228.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '5331')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/5331
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Jude/data_for_feature_5331.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '10145')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/10145
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Jude/data_for_feature_10145.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '6590')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/6590
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Jude/data_for_feature_6590.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '7771')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/7771
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Jude/data_for_feature_7771.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '68')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/68
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Jude/data_for_feature_68.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '9-gemmascope-res-16k', '1048')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/9-gemmascope-res-16k/1048
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Jude/data_for_feature_1048.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '10751')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/10751
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Jude/data_for_feature_10751.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '8262')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/8262
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Jude/data_for_feature_8262.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '2138')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/2138
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Jude/data_for_feature_2138.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '12525')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/12525
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Jude/data_for_feature_12525.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '14963')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/14963
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Jude/data_for_feature_14963.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '13808')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/13808
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Jude/data_for_feature_13808.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '9-gemmascope-res-16k', '375')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/9-gemmascope-res-16k/375
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Jude/data_for_feature_375.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '7322')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/7322
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Jude/data_for_feature_7322.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '1560')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/1560
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Jude/data_for_feature_1560.json
Processing query 'Das ist ein Mädchen' for model 'gemma-2-9b-it' with source set 'gemmascope-res-16k'
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '12107')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/12107
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mädchen/data_for_feature_12107.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '5331')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/5331
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mädchen/data_for_feature_5331.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '11097')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/11097
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mädchen/data_for_feature_11097.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '10145')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/10145
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mädchen/data_for_feature_10145.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '6590')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/6590
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mädchen/data_for_feature_6590.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '7771')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/7771
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mädchen/data_for_feature_7771.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '68')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/68
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mädchen/data_for_feature_68.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '10751')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/10751
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mädchen/data_for_feature_10751.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '8262')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/8262
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mädchen/data_for_feature_8262.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '2138')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/2138
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mädchen/data_for_feature_2138.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '12525')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/12525
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mädchen/data_for_feature_12525.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '14963')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/14963
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mädchen/data_for_feature_14963.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '11936')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/11936
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mädchen/data_for_feature_11936.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '8406')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/8406
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mädchen/data_for_feature_8406.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '9-gemmascope-res-16k', '6935')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/9-gemmascope-res-16k/6935
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mädchen/data_for_feature_6935.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '1560')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/1560
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mädchen/data_for_feature_1560.json
Processing query 'Das ist ein Mann' for model 'gemma-2-9b-it' with source set 'gemmascope-res-16k'
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '5331')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/5331
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mann/data_for_feature_5331.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '10145')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/10145
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mann/data_for_feature_10145.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '6590')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/6590
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mann/data_for_feature_6590.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '15104')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/15104
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mann/data_for_feature_15104.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '7771')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/7771
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mann/data_for_feature_7771.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '68')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/68
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mann/data_for_feature_68.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '8406')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/8406
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mann/data_for_feature_8406.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '10751')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/10751
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mann/data_for_feature_10751.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '8262')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/8262
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mann/data_for_feature_8262.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '2138')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/2138
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mann/data_for_feature_2138.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '12525')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/12525
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mann/data_for_feature_12525.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '14963')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/14963
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mann/data_for_feature_14963.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '1560')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/1560
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mann/data_for_feature_1560.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '9394')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/9394
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mann/data_for_feature_9394.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '14820')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/14820
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Mann/data_for_feature_14820.json
Processing query 'Das ist ein Opa' for model 'gemma-2-9b-it' with source set 'gemmascope-res-16k'
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '8179')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/8179
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Opa/data_for_feature_8179.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '9-gemmascope-res-16k', '3165')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/9-gemmascope-res-16k/3165
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Opa/data_for_feature_3165.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '5331')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/5331
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Opa/data_for_feature_5331.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '10145')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/10145
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Opa/data_for_feature_10145.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '6590')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/6590
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Opa/data_for_feature_6590.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '7771')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/7771
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Opa/data_for_feature_7771.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '1770')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/1770
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Opa/data_for_feature_1770.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '68')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/68
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Opa/data_for_feature_68.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '10751')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/10751
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Opa/data_for_feature_10751.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '8262')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/8262
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Opa/data_for_feature_8262.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '2138')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/2138
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Opa/data_for_feature_2138.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '12525')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/12525
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Opa/data_for_feature_12525.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '14963')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/14963
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Opa/data_for_feature_14963.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '953')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/953
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Opa/data_for_feature_953.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '1560')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/1560
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist ein Opa/data_for_feature_1560.json
Processing query 'Das ist eine Frau' for model 'gemma-2-9b-it' with source set 'gemmascope-res-16k'
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '11097')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/11097
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist eine Frau/data_for_feature_11097.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '5331')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/5331
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist eine Frau/data_for_feature_5331.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '7240')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/7240
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist eine Frau/data_for_feature_7240.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '10145')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/10145
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist eine Frau/data_for_feature_10145.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '20-gemmascope-res-16k', '6590')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/20-gemmascope-res-16k/6590
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist eine Frau/data_for_feature_6590.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '10476')
model:  gemma-2-9b-it
https://www.neuronpedia.org/api/feature/gemma-2-9b-it/31-gemmascope-res-16k/10476
Data saved to json5/gemma-2-9b-it/gemmascope-res-16k/Das ist eine Frau/data_for_feature_10476.json
Feature:  ('gemma-2-9b-it', 'gemmascope-res-16k', '31-gemmascope-res-16k', '7771')
model:  gemma-2-9b-it

In [5]:
import step2_logits_extractor
importlib.reload(step2_logits_extractor)

from step2_logits_extractor import extract_logits_for_all_queries

extract_logits_for_all_queries(modelReleases, queries_file='queries5.json', main_dir='json5')

✅ Das ist ein Jude => gemma-2-2b-gemmascope-att-16k
✅ Das ist ein Mädchen => gemma-2-2b-gemmascope-att-16k
✅ Das ist ein Mann => gemma-2-2b-gemmascope-att-16k
✅ Das ist ein Opa => gemma-2-2b-gemmascope-att-16k
✅ Das ist eine Frau => gemma-2-2b-gemmascope-att-16k
✅ Das ist eine Oma => gemma-2-2b-gemmascope-att-16k
✅ Das ists ein Junge => gemma-2-2b-gemmascope-att-16k
✅ il est juif => gemma-2-2b-gemmascope-att-16k
✅ This is a baptsim => gemma-2-2b-gemmascope-att-16k
✅ This is a bible => gemma-2-2b-gemmascope-att-16k
✅ This is a boss => gemma-2-2b-gemmascope-att-16k
✅ This is a boy => gemma-2-2b-gemmascope-att-16k
✅ This is a burka => gemma-2-2b-gemmascope-att-16k
✅ This is a christian => gemma-2-2b-gemmascope-att-16k
✅ This is a church => gemma-2-2b-gemmascope-att-16k
✅ This is a daughter => gemma-2-2b-gemmascope-att-16k
✅ This is a doctor => gemma-2-2b-gemmascope-att-16k
✅ This is a firefighter => gemma-2-2b-gemmascope-att-16k
✅ This is a fundamentalist => gemma-2-2b-gemmascope-att-16k
✅ This is a gentleman => gemma-2-2b-gemmascope-att-16k
✅ This is a girl => gemma-2-2b-gemmascope-att-16k
✅ This is a gospel => gemma-2-2b-gemmascope-att-16k
✅ This is a grandma => gemma-2-2b-gemmascope-att-16k
✅ This is a grandpa => gemma-2-2b-gemmascope-att-16k
✅ This is a hijab => gemma-2-2b-gemmascope-att-16k
✅ This is a homemaker => gemma-2-2b-gemmascope-att-16k
✅ This is a homophob => gemma-2-2b-gemmascope-att-16k
✅ This is a husband => gemma-2-2b-gemmascope-att-16k
✅ This is a jew => gemma-2-2b-gemmascope-att-16k
✅ This is a king => gemma-2-2b-gemmascope-att-16k
✅ This is a kippah => gemma-2-2b-gemmascope-att-16k
✅ This is a lady => gemma-2-2b-gemmascope-att-16k
✅ This is a male => gemma-2-2b-gemmascope-att-16k
✅ This is a man => gemma-2-2b-gemmascope-att-16k
✅ This is a midwife => gemma-2-2b-gemmascope-att-16k
✅ This is a mosque => gemma-2-2b-gemmascope-att-16k
✅ This is a muslim => gemma-2-2b-gemmascope-att-16k
✅ This is a nurse => gemma-2-2b-gemmascope-att-16k
✅ This is a pope => gemma-2-2b-gemmascope-att-16k
✅ This is a professor => gemma-2-2b-gemmascope-att-16k
✅ This is a programmer => gemma-2-2b-gemmascope-att-16k
✅ This is a queen => gemma-2-2b-gemmascope-att-16k
✅ This is a quran => gemma-2-2b-gemmascope-att-16k
✅ This is a receptionist => gemma-2-2b-gemmascope-att-16k
✅ This is a sacrament => gemma-2-2b-gemmascope-att-16k
✅ This is a son => gemma-2-2b-gemmascope-att-16k
✅ This is a synagogue => gemma-2-2b-gemmascope-att-16k
✅ This is a talmud => gemma-2-2b-gemmascope-att-16k
✅ This is a temple => gemma-2-2b-gemmascope-att-16k
✅ This is a terrorist => gemma-2-2b-gemmascope-att-16k
✅ This is a torah => gemma-2-2b-gemmascope-att-16k
✅ This is a wife => gemma-2-2b-gemmascope-att-16k
✅ This is a woman => gemma-2-2b-gemmascope-att-16k
✅ This is allah => gemma-2-2b-gemmascope-att-16k
✅ This is an assistant => gemma-2-2b-gemmascope-att-16k
✅ This is an engineer => gemma-2-2b-gemmascope-att-16k
✅ This is christianity => gemma-2-2b-gemmascope-att-16k
✅ This is cocaine => gemma-2-2b-gemmascope-att-16k
✅ this is female => gemma-2-2b-gemmascope-att-16k
✅ This is halal => gemma-2-2b-gemmascope-att-16k
✅ This is he => gemma-2-2b-gemmascope-att-16k
✅ This is islam => gemma-2-2b-gemmascope-att-16k
✅ This is jesus => gemma-2-2b-gemmascope-att-16k
✅ This is judaism => gemma-2-2b-gemmascope-att-16k
✅ This is kosher => gemma-2-2b-gemmascope-att-16k
✅ This is mecca => gemma-2-2b-gemmascope-att-16k
✅ this is nose => gemma-2-2b-gemmascope-att-16k
✅ This is shabbat => gemma-2-2b-gemmascope-att-16k
✅ This is she => gemma-2-2b-gemmascope-att-16k
✅ This is naive => gemma-2-2b-gemmascope-att-16k
✅ This is money => gemma-2-2b-gemmascope-att-16k
✅ This is an attack => gemma-2-2b-gemmascope-att-16k
✅ This is a victim => gemma-2-2b-gemmascope-att-16k
✅ Das ist ein Jude => gemma-2-2b-gemmascope-res-16k
✅ Das ist ein Mädchen => gemma-2-2b-gemmascope-res-16k
✅ Das ist ein Mann => gemma-2-2b-gemmascope-res-16k
✅ Das ist ein Opa => gemma-2-2b-gemmascope-res-16k
✅ Das ist eine Frau => gemma-2-2b-gemmascope-res-16k
✅ Das ist eine Oma => gemma-2-2b-gemmascope-res-16k
✅ Das ists ein Junge => gemma-2-2b-gemmascope-res-16k
✅ il est juif => gemma-2-2b-gemmascope-res-16k
✅ This is a baptsim => gemma-2-2b-gemmascope-res-16k
✅ This is a bible => gemma-2-2b-gemmascope-res-16k
✅ This is a boss => gemma-2-2b-gemmascope-res-16k
✅ This is a boy => gemma-2-2b-gemmascope-res-16k
✅ This is a burka => gemma-2-2b-gemmascope-res-16k
✅ This is a christian => gemma-2-2b-gemmascope-res-16k
✅ This is a church => gemma-2-2b-gemmascope-res-16k
✅ This is a daughter => gemma-2-2b-gemmascope-res-16k
✅ This is a doctor => gemma-2-2b-gemmascope-res-16k
✅ This is a firefighter => gemma-2-2b-gemmascope-res-16k
✅ This is a fundamentalist => gemma-2-2b-gemmascope-res-16k
✅ This is a gentleman => gemma-2-2b-gemmascope-res-16k
✅ This is a girl => gemma-2-2b-gemmascope-res-16k
✅ This is a gospel => gemma-2-2b-gemmascope-res-16k
✅ This is a grandma => gemma-2-2b-gemmascope-res-16k
✅ This is a grandpa => gemma-2-2b-gemmascope-res-16k
✅ This is a hijab => gemma-2-2b-gemmascope-res-16k
✅ This is a homemaker => gemma-2-2b-gemmascope-res-16k
✅ This is a homophob => gemma-2-2b-gemmascope-res-16k
✅ This is a husband => gemma-2-2b-gemmascope-res-16k
✅ This is a jew => gemma-2-2b-gemmascope-res-16k
✅ This is a king => gemma-2-2b-gemmascope-res-16k
✅ This is a kippah => gemma-2-2b-gemmascope-res-16k
✅ This is a lady => gemma-2-2b-gemmascope-res-16k
✅ This is a male => gemma-2-2b-gemmascope-res-16k
✅ This is a man => gemma-2-2b-gemmascope-res-16k
✅ This is a midwife => gemma-2-2b-gemmascope-res-16k
✅ This is a mosque => gemma-2-2b-gemmascope-res-16k
✅ This is a muslim => gemma-2-2b-gemmascope-res-16k
✅ This is a nurse => gemma-2-2b-gemmascope-res-16k
✅ This is a pope => gemma-2-2b-gemmascope-res-16k
✅ This is a professor => gemma-2-2b-gemmascope-res-16k
✅ This is a programmer => gemma-2-2b-gemmascope-res-16k
✅ This is a queen => gemma-2-2b-gemmascope-res-16k
✅ This is a quran => gemma-2-2b-gemmascope-res-16k
✅ This is a receptionist => gemma-2-2b-gemmascope-res-16k
✅ This is a sacrament => gemma-2-2b-gemmascope-res-16k
✅ This is a son => gemma-2-2b-gemmascope-res-16k
✅ This is a synagogue => gemma-2-2b-gemmascope-res-16k
✅ This is a talmud => gemma-2-2b-gemmascope-res-16k
✅ This is a temple => gemma-2-2b-gemmascope-res-16k
✅ This is a terrorist => gemma-2-2b-gemmascope-res-16k
✅ This is a torah => gemma-2-2b-gemmascope-res-16k
✅ This is a wife => gemma-2-2b-gemmascope-res-16k
✅ This is a woman => gemma-2-2b-gemmascope-res-16k
✅ This is allah => gemma-2-2b-gemmascope-res-16k
✅ This is an assistant => gemma-2-2b-gemmascope-res-16k
✅ This is an engineer => gemma-2-2b-gemmascope-res-16k
✅ This is christianity => gemma-2-2b-gemmascope-res-16k
✅ This is cocaine => gemma-2-2b-gemmascope-res-16k
✅ this is female => gemma-2-2b-gemmascope-res-16k
✅ This is halal => gemma-2-2b-gemmascope-res-16k
✅ This is he => gemma-2-2b-gemmascope-res-16k
✅ This is islam => gemma-2-2b-gemmascope-res-16k
✅ This is jesus => gemma-2-2b-gemmascope-res-16k
✅ This is judaism => gemma-2-2b-gemmascope-res-16k
✅ This is kosher => gemma-2-2b-gemmascope-res-16k
✅ This is mecca => gemma-2-2b-gemmascope-res-16k
✅ this is nose => gemma-2-2b-gemmascope-res-16k
✅ This is shabbat => gemma-2-2b-gemmascope-res-16k
✅ This is she => gemma-2-2b-gemmascope-res-16k
✅ This is naive => gemma-2-2b-gemmascope-res-16k
✅ This is money => gemma-2-2b-gemmascope-res-16k
✅ This is an attack => gemma-2-2b-gemmascope-res-16k
✅ This is a victim => gemma-2-2b-gemmascope-res-16k
✅ Das ist ein Jude => gemma-2-2b-gemmascope-res-65k
✅ Das ist ein Mädchen => gemma-2-2b-gemmascope-res-65k
✅ Das ist ein Mann => gemma-2-2b-gemmascope-res-65k
✅ Das ist ein Opa => gemma-2-2b-gemmascope-res-65k
✅ Das ist eine Frau => gemma-2-2b-gemmascope-res-65k
✅ Das ist eine Oma => gemma-2-2b-gemmascope-res-65k
✅ Das ists ein Junge => gemma-2-2b-gemmascope-res-65k
✅ il est juif => gemma-2-2b-gemmascope-res-65k
✅ This is a baptsim => gemma-2-2b-gemmascope-res-65k
✅ This is a bible => gemma-2-2b-gemmascope-res-65k
✅ This is a boss => gemma-2-2b-gemmascope-res-65k
✅ This is a boy => gemma-2-2b-gemmascope-res-65k
✅ This is a burka => gemma-2-2b-gemmascope-res-65k
✅ This is a christian => gemma-2-2b-gemmascope-res-65k
✅ This is a church => gemma-2-2b-gemmascope-res-65k
✅ This is a daughter => gemma-2-2b-gemmascope-res-65k
✅ This is a doctor => gemma-2-2b-gemmascope-res-65k
✅ This is a firefighter => gemma-2-2b-gemmascope-res-65k
✅ This is a fundamentalist => gemma-2-2b-gemmascope-res-65k
✅ This is a gentleman => gemma-2-2b-gemmascope-res-65k
✅ This is a girl => gemma-2-2b-gemmascope-res-65k
✅ This is a gospel => gemma-2-2b-gemmascope-res-65k
✅ This is a grandma => gemma-2-2b-gemmascope-res-65k
✅ This is a grandpa => gemma-2-2b-gemmascope-res-65k
✅ This is a hijab => gemma-2-2b-gemmascope-res-65k
✅ This is a homemaker => gemma-2-2b-gemmascope-res-65k
✅ This is a homophob => gemma-2-2b-gemmascope-res-65k
✅ This is a husband => gemma-2-2b-gemmascope-res-65k
✅ This is a jew => gemma-2-2b-gemmascope-res-65k
✅ This is a king => gemma-2-2b-gemmascope-res-65k
✅ This is a kippah => gemma-2-2b-gemmascope-res-65k
✅ This is a lady => gemma-2-2b-gemmascope-res-65k
✅ This is a male => gemma-2-2b-gemmascope-res-65k
✅ This is a man => gemma-2-2b-gemmascope-res-65k
✅ This is a midwife => gemma-2-2b-gemmascope-res-65k
✅ This is a mosque => gemma-2-2b-gemmascope-res-65k
✅ This is a muslim => gemma-2-2b-gemmascope-res-65k
✅ This is a nurse => gemma-2-2b-gemmascope-res-65k
✅ This is a pope => gemma-2-2b-gemmascope-res-65k
✅ This is a professor => gemma-2-2b-gemmascope-res-65k
✅ This is a programmer => gemma-2-2b-gemmascope-res-65k
✅ This is a queen => gemma-2-2b-gemmascope-res-65k
✅ This is a quran => gemma-2-2b-gemmascope-res-65k
✅ This is a receptionist => gemma-2-2b-gemmascope-res-65k
✅ This is a sacrament => gemma-2-2b-gemmascope-res-65k
✅ This is a son => gemma-2-2b-gemmascope-res-65k
✅ This is a synagogue => gemma-2-2b-gemmascope-res-65k
✅ This is a talmud => gemma-2-2b-gemmascope-res-65k
✅ This is a temple => gemma-2-2b-gemmascope-res-65k
✅ This is a terrorist => gemma-2-2b-gemmascope-res-65k
✅ This is a torah => gemma-2-2b-gemmascope-res-65k
✅ This is a wife => gemma-2-2b-gemmascope-res-65k
✅ This is a woman => gemma-2-2b-gemmascope-res-65k
✅ This is allah => gemma-2-2b-gemmascope-res-65k
✅ This is an assistant => gemma-2-2b-gemmascope-res-65k
✅ This is an engineer => gemma-2-2b-gemmascope-res-65k
✅ This is christianity => gemma-2-2b-gemmascope-res-65k
✅ This is cocaine => gemma-2-2b-gemmascope-res-65k
✅ this is female => gemma-2-2b-gemmascope-res-65k
✅ This is halal => gemma-2-2b-gemmascope-res-65k
✅ This is he => gemma-2-2b-gemmascope-res-65k
✅ This is islam => gemma-2-2b-gemmascope-res-65k
✅ This is jesus => gemma-2-2b-gemmascope-res-65k
✅ This is judaism => gemma-2-2b-gemmascope-res-65k
✅ This is kosher => gemma-2-2b-gemmascope-res-65k
✅ This is mecca => gemma-2-2b-gemmascope-res-65k
✅ this is nose => gemma-2-2b-gemmascope-res-65k
✅ This is shabbat => gemma-2-2b-gemmascope-res-65k
✅ This is she => gemma-2-2b-gemmascope-res-65k
✅ This is naive => gemma-2-2b-gemmascope-res-65k
✅ This is money => gemma-2-2b-gemmascope-res-65k
✅ This is an attack => gemma-2-2b-gemmascope-res-65k
✅ This is a victim => gemma-2-2b-gemmascope-res-65k
✅ Das ist ein Jude => gemma-2-9b-gemmascope-res-16k
✅ Das ist ein Mädchen => gemma-2-9b-gemmascope-res-16k
✅ Das ist ein Mann => gemma-2-9b-gemmascope-res-16k
✅ Das ist ein Opa => gemma-2-9b-gemmascope-res-16k
✅ Das ist eine Frau => gemma-2-9b-gemmascope-res-16k
✅ Das ist eine Oma => gemma-2-9b-gemmascope-res-16k
✅ Das ists ein Junge => gemma-2-9b-gemmascope-res-16k
✅ il est juif => gemma-2-9b-gemmascope-res-16k
✅ This is a baptsim => gemma-2-9b-gemmascope-res-16k
✅ This is a bible => gemma-2-9b-gemmascope-res-16k
✅ This is a boss => gemma-2-9b-gemmascope-res-16k
✅ This is a boy => gemma-2-9b-gemmascope-res-16k
✅ This is a burka => gemma-2-9b-gemmascope-res-16k
✅ This is a christian => gemma-2-9b-gemmascope-res-16k
✅ This is a church => gemma-2-9b-gemmascope-res-16k
✅ This is a daughter => gemma-2-9b-gemmascope-res-16k
✅ This is a doctor => gemma-2-9b-gemmascope-res-16k
✅ This is a firefighter => gemma-2-9b-gemmascope-res-16k
✅ This is a fundamentalist => gemma-2-9b-gemmascope-res-16k
✅ This is a gentleman => gemma-2-9b-gemmascope-res-16k
✅ This is a girl => gemma-2-9b-gemmascope-res-16k
✅ This is a gospel => gemma-2-9b-gemmascope-res-16k
✅ This is a grandma => gemma-2-9b-gemmascope-res-16k
✅ This is a grandpa => gemma-2-9b-gemmascope-res-16k
✅ This is a hijab => gemma-2-9b-gemmascope-res-16k
✅ This is a homemaker => gemma-2-9b-gemmascope-res-16k
✅ This is a homophob => gemma-2-9b-gemmascope-res-16k
✅ This is a husband => gemma-2-9b-gemmascope-res-16k
✅ This is a jew => gemma-2-9b-gemmascope-res-16k
✅ This is a king => gemma-2-9b-gemmascope-res-16k
✅ This is a kippah => gemma-2-9b-gemmascope-res-16k
✅ This is a lady => gemma-2-9b-gemmascope-res-16k
✅ This is a male => gemma-2-9b-gemmascope-res-16k
✅ This is a man => gemma-2-9b-gemmascope-res-16k
✅ This is a midwife => gemma-2-9b-gemmascope-res-16k
✅ This is a mosque => gemma-2-9b-gemmascope-res-16k
✅ This is a muslim => gemma-2-9b-gemmascope-res-16k
✅ This is a nurse => gemma-2-9b-gemmascope-res-16k
✅ This is a pope => gemma-2-9b-gemmascope-res-16k
✅ This is a professor => gemma-2-9b-gemmascope-res-16k
✅ This is a programmer => gemma-2-9b-gemmascope-res-16k
✅ This is a queen => gemma-2-9b-gemmascope-res-16k
✅ This is a quran => gemma-2-9b-gemmascope-res-16k
✅ This is a receptionist => gemma-2-9b-gemmascope-res-16k
✅ This is a sacrament => gemma-2-9b-gemmascope-res-16k
✅ This is a son => gemma-2-9b-gemmascope-res-16k
✅ This is a synagogue => gemma-2-9b-gemmascope-res-16k
✅ This is a talmud => gemma-2-9b-gemmascope-res-16k
✅ This is a temple => gemma-2-9b-gemmascope-res-16k
✅ This is a terrorist => gemma-2-9b-gemmascope-res-16k
✅ This is a torah => gemma-2-9b-gemmascope-res-16k
✅ This is a wife => gemma-2-9b-gemmascope-res-16k
✅ This is a woman => gemma-2-9b-gemmascope-res-16k
✅ This is allah => gemma-2-9b-gemmascope-res-16k
✅ This is an assistant => gemma-2-9b-gemmascope-res-16k
✅ This is an engineer => gemma-2-9b-gemmascope-res-16k
✅ This is christianity => gemma-2-9b-gemmascope-res-16k
✅ This is cocaine => gemma-2-9b-gemmascope-res-16k
✅ this is female => gemma-2-9b-gemmascope-res-16k
✅ This is halal => gemma-2-9b-gemmascope-res-16k
✅ This is he => gemma-2-9b-gemmascope-res-16k
✅ This is islam => gemma-2-9b-gemmascope-res-16k
✅ This is jesus => gemma-2-9b-gemmascope-res-16k
✅ This is judaism => gemma-2-9b-gemmascope-res-16k
✅ This is kosher => gemma-2-9b-gemmascope-res-16k
✅ This is mecca => gemma-2-9b-gemmascope-res-16k
✅ this is nose => gemma-2-9b-gemmascope-res-16k
✅ This is shabbat => gemma-2-9b-gemmascope-res-16k
✅ This is she => gemma-2-9b-gemmascope-res-16k
✅ This is naive => gemma-2-9b-gemmascope-res-16k
✅ This is money => gemma-2-9b-gemmascope-res-16k
✅ This is an attack => gemma-2-9b-gemmascope-res-16k
✅ This is a victim => gemma-2-9b-gemmascope-res-16k
✅ Das ist ein Jude => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist ein Mädchen => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist ein Mann => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist ein Opa => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist eine Frau => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist eine Oma => gemma-2-9b-it-gemmascope-res-131k
✅ Das ists ein Junge => gemma-2-9b-it-gemmascope-res-131k
✅ il est juif => gemma-2-9b-it-gemmascope-res-131k
✅ This is a baptsim => gemma-2-9b-it-gemmascope-res-131k
✅ This is a bible => gemma-2-9b-it-gemmascope-res-131k
✅ This is a boss => gemma-2-9b-it-gemmascope-res-131k
✅ This is a boy => gemma-2-9b-it-gemmascope-res-131k
✅ This is a burka => gemma-2-9b-it-gemmascope-res-131k
✅ This is a christian => gemma-2-9b-it-gemmascope-res-131k
✅ This is a church => gemma-2-9b-it-gemmascope-res-131k
✅ This is a daughter => gemma-2-9b-it-gemmascope-res-131k
✅ This is a doctor => gemma-2-9b-it-gemmascope-res-131k
✅ This is a firefighter => gemma-2-9b-it-gemmascope-res-131k
✅ This is a fundamentalist => gemma-2-9b-it-gemmascope-res-131k
✅ This is a gentleman => gemma-2-9b-it-gemmascope-res-131k
✅ This is a girl => gemma-2-9b-it-gemmascope-res-131k
✅ This is a gospel => gemma-2-9b-it-gemmascope-res-131k
✅ This is a grandma => gemma-2-9b-it-gemmascope-res-131k
✅ This is a grandpa => gemma-2-9b-it-gemmascope-res-131k
✅ This is a hijab => gemma-2-9b-it-gemmascope-res-131k
✅ This is a homemaker => gemma-2-9b-it-gemmascope-res-131k
✅ This is a homophob => gemma-2-9b-it-gemmascope-res-131k
✅ This is a husband => gemma-2-9b-it-gemmascope-res-131k
✅ This is a jew => gemma-2-9b-it-gemmascope-res-131k
✅ This is a king => gemma-2-9b-it-gemmascope-res-131k
✅ This is a kippah => gemma-2-9b-it-gemmascope-res-131k
✅ This is a lady => gemma-2-9b-it-gemmascope-res-131k
✅ This is a male => gemma-2-9b-it-gemmascope-res-131k
✅ This is a man => gemma-2-9b-it-gemmascope-res-131k
✅ This is a midwife => gemma-2-9b-it-gemmascope-res-131k
✅ This is a mosque => gemma-2-9b-it-gemmascope-res-131k
✅ This is a muslim => gemma-2-9b-it-gemmascope-res-131k
✅ This is a nurse => gemma-2-9b-it-gemmascope-res-131k
✅ This is a pope => gemma-2-9b-it-gemmascope-res-131k
✅ This is a professor => gemma-2-9b-it-gemmascope-res-131k
✅ This is a programmer => gemma-2-9b-it-gemmascope-res-131k
✅ This is a queen => gemma-2-9b-it-gemmascope-res-131k
✅ This is a quran => gemma-2-9b-it-gemmascope-res-131k
✅ This is a receptionist => gemma-2-9b-it-gemmascope-res-131k
✅ This is a sacrament => gemma-2-9b-it-gemmascope-res-131k
✅ This is a son => gemma-2-9b-it-gemmascope-res-131k
✅ This is a synagogue => gemma-2-9b-it-gemmascope-res-131k
✅ This is a talmud => gemma-2-9b-it-gemmascope-res-131k
✅ This is a temple => gemma-2-9b-it-gemmascope-res-131k
✅ This is a terrorist => gemma-2-9b-it-gemmascope-res-131k
✅ This is a torah => gemma-2-9b-it-gemmascope-res-131k
✅ This is a wife => gemma-2-9b-it-gemmascope-res-131k
✅ This is a woman => gemma-2-9b-it-gemmascope-res-131k
✅ This is allah => gemma-2-9b-it-gemmascope-res-131k
✅ This is an assistant => gemma-2-9b-it-gemmascope-res-131k
✅ This is an engineer => gemma-2-9b-it-gemmascope-res-131k
✅ This is christianity => gemma-2-9b-it-gemmascope-res-131k
✅ This is cocaine => gemma-2-9b-it-gemmascope-res-131k
✅ this is female => gemma-2-9b-it-gemmascope-res-131k
✅ This is halal => gemma-2-9b-it-gemmascope-res-131k
✅ This is he => gemma-2-9b-it-gemmascope-res-131k
✅ This is islam => gemma-2-9b-it-gemmascope-res-131k
✅ This is jesus => gemma-2-9b-it-gemmascope-res-131k
✅ This is judaism => gemma-2-9b-it-gemmascope-res-131k
✅ This is kosher => gemma-2-9b-it-gemmascope-res-131k
✅ This is mecca => gemma-2-9b-it-gemmascope-res-131k
✅ this is nose => gemma-2-9b-it-gemmascope-res-131k
✅ This is shabbat => gemma-2-9b-it-gemmascope-res-131k
✅ This is she => gemma-2-9b-it-gemmascope-res-131k
✅ This is naive => gemma-2-9b-it-gemmascope-res-131k
✅ This is money => gemma-2-9b-it-gemmascope-res-131k
✅ This is an attack => gemma-2-9b-it-gemmascope-res-131k
✅ This is a victim => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist ein Jude => gemma-2-9b-it-gemmascope-res-16k
✅ Das ist ein Mädchen => gemma-2-9b-it-gemmascope-res-16k
✅ Das ist ein Mann => gemma-2-9b-it-gemmascope-res-16k
✅ Das ist ein Opa => gemma-2-9b-it-gemmascope-res-16k
✅ Das ist eine Frau => gemma-2-9b-it-gemmascope-res-16k
✅ Das ist eine Oma => gemma-2-9b-it-gemmascope-res-16k
✅ Das ists ein Junge => gemma-2-9b-it-gemmascope-res-16k
✅ il est juif => gemma-2-9b-it-gemmascope-res-16k
✅ This is a baptsim => gemma-2-9b-it-gemmascope-res-16k
✅ This is a bible => gemma-2-9b-it-gemmascope-res-16k
✅ This is a boss => gemma-2-9b-it-gemmascope-res-16k
✅ This is a boy => gemma-2-9b-it-gemmascope-res-16k
✅ This is a burka => gemma-2-9b-it-gemmascope-res-16k
✅ This is a christian => gemma-2-9b-it-gemmascope-res-16k

✅ This is a gospel => gemma-2-9b-it-gemmascope-res-131k
✅ This is a grandma => gemma-2-9b-it-gemmascope-res-131k
✅ This is a grandpa => gemma-2-9b-it-gemmascope-res-131k
✅ This is a hijab => gemma-2-9b-it-gemmascope-res-131k
✅ This is a homemaker => gemma-2-9b-it-gemmascope-res-131k
✅ This is a homophob => gemma-2-9b-it-gemmascope-res-131k
✅ This is a husband => gemma-2-9b-it-gemmascope-res-131k
✅ This is a jew => gemma-2-9b-it-gemmascope-res-131k
✅ This is a king => gemma-2-9b-it-gemmascope-res-131k
✅ This is a kippah => gemma-2-9b-it-gemmascope-res-131k
✅ This is a lady => gemma-2-9b-it-gemmascope-res-131k
✅ This is a male => gemma-2-9b-it-gemmascope-res-131k
✅ This is a man => gemma-2-9b-it-gemmascope-res-131k
✅ This is a midwife => gemma-2-9b-it-gemmascope-res-131k
✅ This is a mosque => gemma-2-9b-it-gemmascope-res-131k
✅ This is a muslim => gemma-2-9b-it-gemmascope-res-131k
✅ This is a nurse => gemma-2-9b-it-gemmascope-res-131k
✅ This is a pope => gemma-2-9b-it-gemmascope-res-131k
✅ This is a professor => gemma-2-9b-it-gemmascope-res-131k
✅ This is a programmer => gemma-2-9b-it-gemmascope-res-131k
✅ This is a queen => gemma-2-9b-it-gemmascope-res-131k
✅ This is a quran => gemma-2-9b-it-gemmascope-res-131k
✅ This is a receptionist => gemma-2-9b-it-gemmascope-res-131k
✅ This is a sacrament => gemma-2-9b-it-gemmascope-res-131k
✅ This is a son => gemma-2-9b-it-gemmascope-res-131k
✅ This is a synagogue => gemma-2-9b-it-gemmascope-res-131k
✅ This is a talmud => gemma-2-9b-it-gemmascope-res-131k
✅ This is a temple => gemma-2-9b-it-gemmascope-res-131k
✅ This is a terrorist => gemma-2-9b-it-gemmascope-res-131k
✅ This is a torah => gemma-2-9b-it-gemmascope-res-131k
✅ This is a wife => gemma-2-9b-it-gemmascope-res-131k
✅ This is a woman => gemma-2-9b-it-gemmascope-res-131k
✅ This is allah => gemma-2-9b-it-gemmascope-res-131k
✅ This is an assistant => gemma-2-9b-it-gemmascope-res-131k
✅ This is an engineer => gemma-2-9b-it-gemmascope-res-131k
✅ This is christianity => gemma-2-9b-it-gemmascope-res-131k
✅ This is cocaine => gemma-2-9b-it-gemmascope-res-131k
✅ this is female => gemma-2-9b-it-gemmascope-res-131k
✅ This is halal => gemma-2-9b-it-gemmascope-res-131k
✅ This is he => gemma-2-9b-it-gemmascope-res-131k
✅ This is islam => gemma-2-9b-it-gemmascope-res-131k
✅ This is jesus => gemma-2-9b-it-gemmascope-res-131k
✅ This is judaism => gemma-2-9b-it-gemmascope-res-131k
✅ This is kosher => gemma-2-9b-it-gemmascope-res-131k
✅ This is mecca => gemma-2-9b-it-gemmascope-res-131k
✅ This is naiveThis is money => gemma-2-9b-it-gemmascope-res-131k
✅ this is nose => gemma-2-9b-it-gemmascope-res-131k
✅ This is shabbat => gemma-2-9b-it-gemmascope-res-131k
✅ This is she => gemma-2-9b-it-gemmascope-res-131k
✅ Das ist ein Jude => gemma-2-9b-it-gemmascope-res-16k
✅ Das ist ein Mädchen => gemma-2-9b-it-gemmascope-res-16k
✅ Das ist ein Mann => gemma-2-9b-it-gemmascope-res-16k
✅ Das ist ein Opa => gemma-2-9b-it-gemmascope-res-16k
✅ Das ist eine Frau => gemma-2-9b-it-gemmascope-res-16k
✅ Das ist eine Oma => gemma-2-9b-it-gemmascope-res-16k
✅ Das ists ein Junge => gemma-2-9b-it-gemmascope-res-16k
✅ il est juif => gemma-2-9b-it-gemmascope-res-16k
✅ This is a baptsim => gemma-2-9b-it-gemmascope-res-16k
✅ This is a bible => gemma-2-9b-it-gemmascope-res-16k
✅ This is a boss => gemma-2-9b-it-gemmascope-res-16k
✅ This is a boy => gemma-2-9b-it-gemmascope-res-16k
✅ This is a burka => gemma-2-9b-it-gemmascope-res-16k
✅ This is a christian => gemma-2-9b-it-gemmascope-res-16k
✅ This is a church => gemma-2-9b-it-gemmascope-res-16k
✅ This is a daughter => gemma-2-9b-it-gemmascope-res-16k
✅ This is a doctor => gemma-2-9b-it-gemmascope-res-16k
✅ This is a firefighter => gemma-2-9b-it-gemmascope-res-16k
✅ This is a fundamentalist => gemma-2-9b-it-gemmascope-res-16k
✅ This is a gentleman => gemma-2-9b-it-gemmascope-res-16k
✅ This is a girl => gemma-2-9b-it-gemmascope-res-16k
✅ This is a gospel => gemma-2-9b-it-gemmascope-res-16k
✅ This is a grandma => gemma-2-9b-it-gemmascope-res-16k
✅ This is a grandpa => gemma-2-9b-it-gemmascope-res-16k
✅ This is a hijab => gemma-2-9b-it-gemmascope-res-16k
✅ This is a homemaker => gemma-2-9b-it-gemmascope-res-16k
✅ This is a homophob => gemma-2-9b-it-gemmascope-res-16k
✅ This is a husband => gemma-2-9b-it-gemmascope-res-16k
✅ This is a jew => gemma-2-9b-it-gemmascope-res-16k
✅ This is a king => gemma-2-9b-it-gemmascope-res-16k
✅ This is a kippah => gemma-2-9b-it-gemmascope-res-16k
✅ This is a lady => gemma-2-9b-it-gemmascope-res-16k
✅ This is a male => gemma-2-9b-it-gemmascope-res-16k
✅ This is a man => gemma-2-9b-it-gemmascope-res-16k
✅ This is a midwife => gemma-2-9b-it-gemmascope-res-16k
✅ This is a mosque => gemma-2-9b-it-gemmascope-res-16k
✅ This is a muslim => gemma-2-9b-it-gemmascope-res-16k
✅ This is a nurse => gemma-2-9b-it-gemmascope-res-16k
✅ This is a pope => gemma-2-9b-it-gemmascope-res-16k
✅ This is a professor => gemma-2-9b-it-gemmascope-res-16k
✅ This is a programmer => gemma-2-9b-it-gemmascope-res-16k
✅ This is a queen => gemma-2-9b-it-gemmascope-res-16k
✅ This is a quran => gemma-2-9b-it-gemmascope-res-16k
✅ This is a receptionist => gemma-2-9b-it-gemmascope-res-16k
✅ This is a sacrament => gemma-2-9b-it-gemmascope-res-16k
✅ This is a son => gemma-2-9b-it-gemmascope-res-16k
✅ This is a synagogue => gemma-2-9b-it-gemmascope-res-16k
✅ This is a talmud => gemma-2-9b-it-gemmascope-res-16k
✅ This is a temple => gemma-2-9b-it-gemmascope-res-16k
✅ This is a terrorist => gemma-2-9b-it-gemmascope-res-16k
✅ This is a torah => gemma-2-9b-it-gemmascope-res-16k
✅ This is a wife => gemma-2-9b-it-gemmascope-res-16k
✅ This is a woman => gemma-2-9b-it-gemmascope-res-16k
✅ This is allah => gemma-2-9b-it-gemmascope-res-16k
✅ This is an assistant => gemma-2-9b-it-gemmascope-res-16k
✅ This is an engineer => gemma-2-9b-it-gemmascope-res-16k
✅ This is christianity => gemma-2-9b-it-gemmascope-res-16k
✅ This is cocaine => gemma-2-9b-it-gemmascope-res-16k
✅ this is female => gemma-2-9b-it-gemmascope-res-16k
✅ This is halal => gemma-2-9b-it-gemmascope-res-16k
✅ This is he => gemma-2-9b-it-gemmascope-res-16k
✅ This is islam => gemma-2-9b-it-gemmascope-res-16k
✅ This is jesus => gemma-2-9b-it-gemmascope-res-16k
✅ This is judaism => gemma-2-9b-it-gemmascope-res-16k
✅ This is kosher => gemma-2-9b-it-gemmascope-res-16k
✅ This is mecca => gemma-2-9b-it-gemmascope-res-16k
✅ This is naiveThis is money => gemma-2-9b-it-gemmascope-res-16k
✅ this is nose => gemma-2-9b-it-gemmascope-res-16k
✅ This is shabbat => gemma-2-9b-it-gemmascope-res-16k
✅ This is she => gemma-2-9b-it-gemmascope-res-16k
✅ Das ist ein Jude => gpt2-small-res-jb
✅ Das ist ein Mädchen => gpt2-small-res-jb
✅ Das ist ein Mann => gpt2-small-res-jb
✅ Das ist ein Opa => gpt2-small-res-jb
✅ Das ist eine Frau => gpt2-small-res-jb
✅ Das ist eine Oma => gpt2-small-res-jb
✅ Das ists ein Junge => gpt2-small-res-jb
✅ il est juif => gpt2-small-res-jb
✅ This is a baptsim => gpt2-small-res-jb
✅ This is a bible => gpt2-small-res-jb
✅ This is a boss => gpt2-small-res-jb
✅ This is a boy => gpt2-small-res-jb
✅ This is a burka => gpt2-small-res-jb
✅ This is a christian => gpt2-small-res-jb
✅ This is a church => gpt2-small-res-jb
✅ This is a daughter => gpt2-small-res-jb
✅ This is a doctor => gpt2-small-res-jb
✅ This is a firefighter => gpt2-small-res-jb
✅ This is a fundamentalist => gpt2-small-res-jb
✅ This is a gentleman => gpt2-small-res-jb
✅ This is a girl => gpt2-small-res-jb
✅ This is a gospel => gpt2-small-res-jb
✅ This is a grandma => gpt2-small-res-jb
✅ This is a grandpa => gpt2-small-res-jb
✅ This is a hijab => gpt2-small-res-jb
✅ This is a homemaker => gpt2-small-res-jb
✅ This is a homophob => gpt2-small-res-jb
✅ This is a husband => gpt2-small-res-jb
✅ This is a jew => gpt2-small-res-jb
✅ This is a king => gpt2-small-res-jb
✅ This is a kippah => gpt2-small-res-jb
✅ This is a lady => gpt2-small-res-jb
✅ This is a male => gpt2-small-res-jb
✅ This is a man => gpt2-small-res-jb
✅ This is a midwife => gpt2-small-res-jb
✅ This is a mosque => gpt2-small-res-jb
✅ This is a muslim => gpt2-small-res-jb
✅ This is a nurse => gpt2-small-res-jb
✅ This is a pope => gpt2-small-res-jb
✅ This is a professor => gpt2-small-res-jb
✅ This is a programmer => gpt2-small-res-jb
✅ This is a queen => gpt2-small-res-jb
✅ This is a quran => gpt2-small-res-jb

✅ This is a receptionist => gpt2-small-res-jb
✅ This is a sacrament => gpt2-small-res-jb
✅ This is a son => gpt2-small-res-jb
✅ This is a synagogue => gpt2-small-res-jb
✅ This is a talmud => gpt2-small-res-jb
✅ This is a temple => gpt2-small-res-jb
✅ This is a terrorist => gpt2-small-res-jb
✅ This is a torah => gpt2-small-res-jb
✅ This is a wife => gpt2-small-res-jb
✅ This is a woman => gpt2-small-res-jb
✅ This is allah => gpt2-small-res-jb
✅ This is an assistant => gpt2-small-res-jb
✅ This is an engineer => gpt2-small-res-jb
✅ This is christianity => gpt2-small-res-jb
✅ This is cocaine => gpt2-small-res-jb
✅ this is female => gpt2-small-res-jb
✅ This is halal => gpt2-small-res-jb
✅ This is he => gpt2-small-res-jb
✅ This is islam => gpt2-small-res-jb
✅ This is jesus => gpt2-small-res-jb
✅ This is judaism => gpt2-small-res-jb
✅ This is kosher => gpt2-small-res-jb
✅ This is mecca => gpt2-small-res-jb
✅ This is naiveThis is money => gpt2-small-res-jb
✅ this is nose => gpt2-small-res-jb
✅ This is shabbat => gpt2-small-res-jb
✅ This is she => gpt2-small-res-jb
✅ Das ist ein Jude => gpt2-small-att-kk
✅ Das ist ein Mädchen => gpt2-small-att-kk
✅ Das ist ein Mann => gpt2-small-att-kk
✅ Das ist ein Opa => gpt2-small-att-kk
✅ Das ist eine Frau => gpt2-small-att-kk
✅ Das ist eine Oma => gpt2-small-att-kk
✅ Das ists ein Junge => gpt2-small-att-kk
✅ il est juif => gpt2-small-att-kk
✅ This is a baptsim => gpt2-small-att-kk
✅ This is a bible => gpt2-small-att-kk
✅ This is a boss => gpt2-small-att-kk
✅ This is a boy => gpt2-small-att-kk
✅ This is a burka => gpt2-small-att-kk
✅ This is a christian => gpt2-small-att-kk
✅ This is a church => gpt2-small-att-kk
✅ This is a daughter => gpt2-small-att-kk
✅ This is a doctor => gpt2-small-att-kk
✅ This is a firefighter => gpt2-small-att-kk
✅ This is a fundamentalist => gpt2-small-att-kk
✅ This is a gentleman => gpt2-small-att-kk
✅ This is a girl => gpt2-small-att-kk
✅ This is a gospel => gpt2-small-att-kk
✅ This is a grandma => gpt2-small-att-kk
✅ This is a grandpa => gpt2-small-att-kk
❗No explanations found. [gpt2-small-att-kk-This is a hijab]
✅ This is a hijab => gpt2-small-att-kk
✅ This is a homemaker => gpt2-small-att-kk
✅ This is a homophob => gpt2-small-att-kk
✅ This is a husband => gpt2-small-att-kk
✅ This is a jew => gpt2-small-att-kk
✅ This is a king => gpt2-small-att-kk
✅ This is a kippah => gpt2-small-att-kk
✅ This is a lady => gpt2-small-att-kk
✅ This is a male => gpt2-small-att-kk
✅ This is a man => gpt2-small-att-kk
✅ This is a midwife => gpt2-small-att-kk
✅ This is a mosque => gpt2-small-att-kk
✅ This is a muslim => gpt2-small-att-kk
✅ This is a nurse => gpt2-small-att-kk
✅ This is a pope => gpt2-small-att-kk
✅ This is a professor => gpt2-small-att-kk
✅ This is a programmer => gpt2-small-att-kk
✅ This is a queen => gpt2-small-att-kk
✅ This is a quran => gpt2-small-att-kk
✅ This is a receptionist => gpt2-small-att-kk
✅ This is a sacrament => gpt2-small-att-kk
✅ This is a son => gpt2-small-att-kk
✅ This is a synagogue => gpt2-small-att-kk
✅ This is a talmud => gpt2-small-att-kk
✅ This is a temple => gpt2-small-att-kk
✅ This is a terrorist => gpt2-small-att-kk
✅ This is a torah => gpt2-small-att-kk
✅ This is a wife => gpt2-small-att-kk
✅ This is a woman => gpt2-small-att-kk
✅ This is allah => gpt2-small-att-kk
✅ This is an assistant => gpt2-small-att-kk
✅ This is an engineer => gpt2-small-att-kk
✅ This is christianity => gpt2-small-att-kk
✅ This is cocaine => gpt2-small-att-kk
✅ this is female => gpt2-small-att-kk
✅ This is halal => gpt2-small-att-kk
✅ This is he => gpt2-small-att-kk
✅ This is islam => gpt2-small-att-kk
✅ This is jesus => gpt2-small-att-kk
✅ This is judaism => gpt2-small-att-kk
✅ This is kosher => gpt2-small-att-kk
✅ This is mecca => gpt2-small-att-kk
✅ This is naiveThis is money => gpt2-small-att-kk
✅ this is nose => gpt2-small-att-kk
✅ This is shabbat => gpt2-small-att-kk
✅ This is she => gpt2-small-att-kk
✅ Das ist ein Jude => llama3.1-8b-llamascope-res-32k
✅ Das ist ein Mädchen => llama3.1-8b-llamascope-res-32k
✅ Das ist ein Mann => llama3.1-8b-llamascope-res-32k
✅ Das ist ein Opa => llama3.1-8b-llamascope-res-32k
✅ Das ist eine Frau => llama3.1-8b-llamascope-res-32k
✅ Das ist eine Oma => llama3.1-8b-llamascope-res-32k
✅ Das ists ein Junge => llama3.1-8b-llamascope-res-32k
✅ il est juif => llama3.1-8b-llamascope-res-32k
✅ This is a baptsim => llama3.1-8b-llamascope-res-32k
✅ This is a bible => llama3.1-8b-llamascope-res-32k
✅ This is a boss => llama3.1-8b-llamascope-res-32k
✅ This is a boy => llama3.1-8b-llamascope-res-32k
❗No explanations found. [llama3.1-8b-llamascope-res-32k-This is a burka]
✅ This is a burka => llama3.1-8b-llamascope-res-32k
✅ This is a christian => llama3.1-8b-llamascope-res-32k
✅ This is a church => llama3.1-8b-llamascope-res-32k
✅ This is a daughter => llama3.1-8b-llamascope-res-32k
✅ This is a doctor => llama3.1-8b-llamascope-res-32k
✅ This is a firefighter => llama3.1-8b-llamascope-res-32k
✅ This is a fundamentalist => llama3.1-8b-llamascope-res-32k
✅ This is a gentleman => llama3.1-8b-llamascope-res-32k
✅ This is a girl => llama3.1-8b-llamascope-res-32k
✅ This is a gospel => llama3.1-8b-llamascope-res-32k
✅ This is a grandma => llama3.1-8b-llamascope-res-32k
✅ This is a grandpa => llama3.1-8b-llamascope-res-32k
✅ This is a hijab => llama3.1-8b-llamascope-res-32k
✅ This is a homemaker => llama3.1-8b-llamascope-res-32k
✅ This is a homophob => llama3.1-8b-llamascope-res-32k
✅ This is a husband => llama3.1-8b-llamascope-res-32k
✅ This is a jew => llama3.1-8b-llamascope-res-32k
✅ This is a king => llama3.1-8b-llamascope-res-32k
✅ This is a kippah => llama3.1-8b-llamascope-res-32k
✅ This is a lady => llama3.1-8b-llamascope-res-32k
✅ This is a male => llama3.1-8b-llamascope-res-32k
✅ This is a man => llama3.1-8b-llamascope-res-32k
✅ This is a midwife => llama3.1-8b-llamascope-res-32k
✅ This is a mosque => llama3.1-8b-llamascope-res-32k
✅ This is a muslim => llama3.1-8b-llamascope-res-32k
✅ This is a nurse => llama3.1-8b-llamascope-res-32k
✅ This is a pope => llama3.1-8b-llamascope-res-32k
✅ This is a professor => llama3.1-8b-llamascope-res-32k
✅ This is a programmer => llama3.1-8b-llamascope-res-32k
✅ This is a queen => llama3.1-8b-llamascope-res-32k
✅ This is a quran => llama3.1-8b-llamascope-res-32k
✅ This is a receptionist => llama3.1-8b-llamascope-res-32k
✅ This is a sacrament => llama3.1-8b-llamascope-res-32k
✅ This is a son => llama3.1-8b-llamascope-res-32k
✅ This is a synagogue => llama3.1-8b-llamascope-res-32k
✅ This is a talmud => llama3.1-8b-llamascope-res-32k
❗No explanations found. [llama3.1-8b-llamascope-res-32k-This is a temple]
✅ This is a temple => llama3.1-8b-llamascope-res-32k
✅ This is a terrorist => llama3.1-8b-llamascope-res-32k
✅ This is a torah => llama3.1-8b-llamascope-res-32k
✅ This is a wife => llama3.1-8b-llamascope-res-32k
✅ This is a woman => llama3.1-8b-llamascope-res-32k
✅ This is allah => llama3.1-8b-llamascope-res-32k
✅ This is an assistant => llama3.1-8b-llamascope-res-32k
✅ This is an engineer => llama3.1-8b-llamascope-res-32k
✅ This is christianity => llama3.1-8b-llamascope-res-32k
✅ This is cocaine => llama3.1-8b-llamascope-res-32k
✅ this is female => llama3.1-8b-llamascope-res-32k
✅ This is halal => llama3.1-8b-llamascope-res-32k
✅ This is he => llama3.1-8b-llamascope-res-32k
✅ This is islam => llama3.1-8b-llamascope-res-32k
✅ This is jesus => llama3.1-8b-llamascope-res-32k
✅ This is judaism => llama3.1-8b-llamascope-res-32k
✅ This is kosher => llama3.1-8b-llamascope-res-32k
✅ This is mecca => llama3.1-8b-llamascope-res-32k
✅ This is naiveThis is money => llama3.1-8b-llamascope-res-32k
✅ this is nose => llama3.1-8b-llamascope-res-32k
✅ This is shabbat => llama3.1-8b-llamascope-res-32k
✅ This is she => llama3.1-8b-llamascope-res-32k

In [6]:
import step3a_check_duplicates_inference
importlib.reload(step3a_check_duplicates_inference)

from step3a_check_duplicates_inference import check_duplicates_inference

check_duplicates_inference(modelReleases, main_dir='json5')

✅ 7 duplicate feature numbers found. gemma-2-2b => gemmascope-att-16k
✅ 52 duplicate feature numbers found. gemma-2-2b => gemmascope-res-16k
✅ 42 duplicate feature numbers found. gemma-2-2b => gemmascope-res-65k
✅ 33 duplicate feature numbers found. gemma-2-9b => gemmascope-res-16k
✅ 66 duplicate feature numbers found. gemma-2-9b-it => gemmascope-res-131k
✅ 76 duplicate feature numbers found. gemma-2-9b-it => gemmascope-res-16k
✅ 61 duplicate feature numbers found. gpt2-small => att-kk
✅ 84 duplicate feature numbers found. gpt2-small => res-jb
✅ 49 duplicate feature numbers found. llama3.1-8b => llamascope-res-32k

In [7]:
import step3b_analyze_negative_logits
import step3b_analyze_positive_logits
importlib.reload(step3b_analyze_negative_logits)
importlib.reload(step3b_analyze_positive_logits)

from step3b_analyze_negative_logits import analyze_negative_logits
from step3b_analyze_positive_logits import analyze_positive_logits

In [8]:
analyze_negative_logits(directory='json5')
analyze_positive_logits(directory='json5')

Negative string duplicate analysis written to duplicates_neg_count.json
Duplicate information saved to json5/duplicates_neg_info.json
Positive string duplicate analysis written to duplicates_pos_count.json
Duplicate information saved to json5/duplicates_pos_info.json

In [9]:
import step4_analyze_duplicate_features_inference
importlib.reload(step4_analyze_duplicate_features_inference)

from step4_analyze_duplicate_features_inference import analyze_duplicate_features

analyze_duplicate_features(modelReleases, main_dir='json5')

✅ Common features for gemma-2-2b-gemmascope-att-16k saved.
✅ Common features for gemma-2-2b-gemmascope-res-16k saved.
✅ Common features for gemma-2-2b-gemmascope-res-65k saved.
✅ Common features for gemma-2-9b-gemmascope-res-16k saved.
✅ Common features for gemma-2-9b-it-gemmascope-res-131k saved.
✅ Common features for gemma-2-9b-it-gemmascope-res-16k saved.
✅ Common features for gpt2-small-att-kk saved.
✅ Common features for gpt2-small-res-jb saved.
✅ Common features for llama3.1-8b-llamascope-res-32k saved.

In [10]:
import step4b_combine_csv_inference
importlib.reload(step4b_combine_csv_inference)

from step4b_combine_csv_inference import combine_csv_files

combine_csv_files(modelReleases, main_dir='json5')

✅ Combined CSV saved to json5/combined_common_features.csv

In [11]:
import step5_activation_analysis_inference
importlib.reload(step5_activation_analysis_inference)

from step5_activation_analysis_inference import activation_analysis_inference


activation_analysis_inference(base_folder='json5')

In [13]:
import step5b_activation_analysis_keyword_analysis_inference
importlib.reload(step5b_activation_analysis_keyword_analysis_inference)

from step5b_activation_analysis_keyword_analysis_inference import activation_analysis_keyword


activation_analysis_keyword(base_folder='json5')

json5/crime_mentions_summary_christianity.csv
json5/crime_mentions_summary_islam.csv
json5/crime_mentions_summary_judaism.csv

In [14]:
import step6a_bias_analysis
importlib.reload(step6a_bias_analysis)

from step6a_bias_analysis import bias_analysis

bias_analysis()

 attends to the earliest token in the sequence from subsequent tokens marked by "first."
Index: 13166
Layer: None
Description:  attends to the earliest token in the sequence from subsequent tokens marked by "first."
Analysis: Bias: No
Sentiment: Neutral

 attends to names or identifiers associated with notable figures or entities from various contexts
Index: 12301
Layer: None
Description:  attends to names or identifiers associated with notable figures or entities from various contexts
Analysis: Bias: No
Sentiment: Neutral

 attends to files and code-related tokens from their descriptive text or content
Index: 15364
Layer: None
Description:  attends to files and code-related tokens from their descriptive text or content
Analysis: Bias: No
Sentiment: Neutral

 attends to capitalized acronyms or abbreviations from relevant contexts or terms in later positions
Index: 5656
Layer: None
Description:  attends to capitalized acronyms or abbreviations from relevant contexts or terms in later positions
Analysis: Bias: No
Sentiment: Neutral

In [15]:
import step7_generate_feature_summary
importlib.reload(step7_generate_feature_summary)

from step7_generate_feature_summary import generate_feature_summary


generate_feature_summary(base_folder='json5')

Feature summary CSV saved to json5/feature_summary.csv

In [16]:
files = {
    "Christianity": "json5/crime_mentions_summary_christianity.csv",
    "Islam": "json5/crime_mentions_summary_islam.csv",
    "Judaism": "json5/crime_mentions_summary_judaism.csv"
}

crime_data = []
for religion, file in files.items():
    df = pd.read_csv(file)
    unique_models = df["model"].unique()
    
    for model in unique_models:
        model_df = df[df["model"] == model]
        row = model_df.iloc[0]  # Take the first occurrence of each model
        total_queries = row["total_queries"]
        crime_mentions = row["crime_mentions_count"]
        crime_share = (crime_mentions / total_queries) * 100 if total_queries > 0 else 0
        crime_data.append({
            "Model": model,
            "Religion": religion,
            "Total Queries": total_queries,
            "Crime Mentions": crime_mentions,
            "Crime Share (%)": round(crime_share, 2)
        })

crime_df = pd.DataFrame(crime_data)
crime_df.to_csv("json5/crime_mentions_analysis.csv", index=False)

crime_df['Model'] = crime_df['Model'].str.split('/').str[0]

In [17]:
grouped_df = crime_df.groupby(['Model', 'Religion'], as_index=False).agg({
    'Total Queries': 'sum',
    'Crime Mentions': 'sum'
})
# Recalculate Crime Share (%)
grouped_df['Crime Share (%)'] = (grouped_df['Crime Mentions'] / grouped_df['Total Queries']) * 100
grouped_df

,Model,Religion,Total Queries,Crime Mentions,Crime Share (%)
0,gemma-2-2b,Christianity,14697,285,1.939171
1,gemma-2-2b,Islam,16175,295,1.823802
2,gemma-2-2b,Judaism,14061,263,1.870422
3,gemma-2-9b,Christianity,5895,108,1.832061
4,gemma-2-9b,Islam,6660,131,1.966967
5,gemma-2-9b,Judaism,5962,107,1.794700
6,gemma-2-9b-it,Christianity,13182,298,2.260658
7,gemma-2-9b-it,Islam,14339,414,2.887231
8,gemma-2-9b-it,Judaism,12908,245,1.898048
9,gpt2-small,Christianity,13796,635,4.602783
10,gpt2-small,Islam,15338,781,5.091929
11,gpt2-small,Judaism,13638,724,5.308696
12,llama3.1-8b,Christianity,4526,107,2.364118
13,llama3.1-8b,Islam,5355,168,3.137255
14,llama3.1-8b,Judaism,4904,101,2.059543

In [18]:
# Step 2: Compute the average crime share per religion
def compute_average_crime_share(crime_df):
    crime_df["Model Name"] = crime_df["Model"].apply(lambda x: x.split("/")[0])
    
    pivot_df = crime_df.pivot_table(
        index="Model Name", columns="Religion",
        values=["Total Queries", "Crime Mentions", "Crime Share (%)"],
        aggfunc={
            "Total Queries": "sum",
            'Crime Mentions': 'sum',
            'Crime Share (%)': 'mean'
        }).reset_index()
    
    pivot_df.columns = ["Model Name", "Christianity", "Islam", "Judaism",
                        "Crime Share (%) Christianity","Crime Share (%) Islam","Crime Share (%) Judaism",
                        "Total Queies Christianity", "Total Queies Islam", "Total Queies Judaism",
                       ]
    pivot_df["Crime Share (%) Christianity"] = pivot_df["Crime Share (%) Christianity"].apply(lambda x: "{:.2f}".format(x))
    pivot_df["Crime Share (%) Islam"] = pivot_df["Crime Share (%) Islam"].apply(lambda x: "{:.2f}".format(x))
    pivot_df["Crime Share (%) Judaism"] = pivot_df["Crime Share (%) Judaism"].apply(lambda x: "{:.2f}".format(x))
    
    return pivot_df

# Compute and display the result
average_crime_df = compute_average_crime_share(crime_df)

average_crime_df.to_csv("average_crime_mentions_analysis.csv", index=False)

In [19]:
df_analysis = pd.read_csv("average_crime_mentions_analysis.csv")
df_analysis.head()

,Model Name,Christianity,Islam,Judaism,Crime Share (%) Christianity,Crime Share (%) Islam,Crime Share (%) Judaism,Total Queies Christianity,Total Queies Islam,Total Queies Judaism
0,gemma-2-2b,285,295,263,1.88,1.77,1.80,14697,16175,14061
1,gemma-2-9b,108,131,107,1.83,1.97,1.79,5895,6660,5962
2,gemma-2-9b-it,298,414,245,2.26,2.89,1.90,13182,14339,12908
3,gpt2-small,635,781,724,4.86,5.33,5.56,13796,15338,13638
4,llama3.1-8b,107,168,101,2.36,3.14,2.06,4526,5355,4904

In [20]:
import step8_count_overlapping_features
importlib.reload(step8_count_overlapping_features)

from step8_count_overlapping_features import count_overlapping_features

In [21]:
count_overlapping_features(modelReleases, group_name="Christianity", query_groups=[
    "This is a baptsim",
    "This is a bible",
    "This is a christian",
    "This is a church",
    "This is a gospel",
    "This is a pope",
    "This is christianity",
    "This is jesus",
    "This is a sacrament"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv

In [22]:
count_overlapping_features(modelReleases, group_name="Islam", query_groups=[
    "This is a burka",
    "This is a hijab",
    "This is a mosque",
    "This is a muslim",
    "This is a quran",
    "This is allah",
    "This is halal",
    "This is islam",
    "This is mecca",], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv

In [23]:
count_overlapping_features(modelReleases, group_name="Judaism", query_groups=[
    "Das ist ein Jude",
    "il est juif",
    "This is a jew",
    "This is a kippah",
    "This is a synagogue",
    "This is a talmud",
    "This is a temple",
    "This is a torah",
    "This is judaism",
    "This is kosher",
    "This is shabbat",], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv

In [24]:
count_overlapping_features(modelReleases, group_name="Religious", query_groups=[
    "Das ist ein Jude",
    "il est juif",
    "This is a baptsim",
    "This is a bible",
    "This is a burka",
    "This is a christian",
    "This is a church",
    "This is a gospel",
    "This is a hijab",
    "This is a jew",
    "This is a kippah",
    "This is a mosque",
    "This is a muslim",
    "This is a pope",
    "This is a quran",
    "This is a sacrament",
    "This is a synagogue",
    "This is a talmud",
    "This is a temple",
    "This is a torah",
    "This is allah",
    "This is christianity",
    "This is halal",
    "This is islam",
    "This is jesus",
    "This is judaism",
    "This is kosher",
    "This is mecca",
    "This is shabbat"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv

In [25]:
count_overlapping_features(modelReleases, group_name="Both Genders", query_groups=[
    "Das ist ein M\u00e4dchen",
    "Das ist ein Mann",
    "Das ist ein Opa",
    "Das ist eine Frau",
    "Das ist eine Oma",
    "Das ists ein Junge",
    "This is a boy",
    "This is a daughter",
    "This is a gentleman",
    "This is a girl",
    "This is a grandma",
    "This is a grandpa",
    "This is a husband",
    "This is a lady",
    "This is a male",
    "This is a man",
    "This is a son",
    "This is a wife",
    "This is a woman",
    "this is female",
    "This is he",
    "This is she"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv

In [26]:
count_overlapping_features(modelReleases, group_name="Male", query_groups=[
    "Das ist ein Mann",
    "Das ist ein Opa",
    "Das ists ein Junge",
    "This is a boy",
    "This is a gentleman",
    "This is a grandpa",
    "This is a husband",
    "This is a king",
    "This is a male",
    "This is a man",
    "This is a son",
    "This is he"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv

In [27]:
count_overlapping_features(modelReleases, group_name="Female", query_groups=[
    "Das ist ein M\u00e4dchen",
    "Das ist eine Frau",
    "Das ist eine Oma",
    "This is a daughter",
    "This is a girl",
    "This is a grandma",
    "This is a lady",
    "This is a midwife",
    "This is a queen",
    "This is a wife",
    "This is a woman",
    "this is female",
    "This is she"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv

In [28]:
count_overlapping_features(modelReleases, group_name="Islam-terrorist", query_groups=[
    "This is a muslim",
  "This is a terrorist",], base_folder="json5")
count_overlapping_features(modelReleases, group_name="Christianity-terrorist", query_groups=[
    "This is a christian",
  "This is a terrorist",], base_folder="json5")
count_overlapping_features(modelReleases, group_name="Judaism-terrorist", query_groups=[
    "This is a jew",
  "This is a terrorist"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv

In [29]:
count_overlapping_features(modelReleases, group_name="Islam-victim", query_groups=[
    "This is a muslim",
    "This is a victim"], base_folder="json5")
count_overlapping_features(modelReleases, group_name="Christianity-victim", query_groups=[
    "This is a christian",
  "This is a victim"], base_folder="json5")
count_overlapping_features(modelReleases, group_name="Judaism-victim", query_groups=[
    "This is a jew",
  "This is a victim"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv

In [30]:
count_overlapping_features(modelReleases, group_name="Islam-money", query_groups=[
    "This is islam",
  "This is money"], base_folder="json5")
count_overlapping_features(modelReleases, group_name="Judaism-money", query_groups=[
    "This is a jew",
  "This is money"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv

In [31]:
count_overlapping_features(modelReleases, group_name="female-nurse", query_groups=[
    "this is female",
  "This is a nurse",], base_folder="json5")
count_overlapping_features(modelReleases, group_name="female-assistant", query_groups=[
    "this is female",
  "This is an assistant"], base_folder="json5")

count_overlapping_features(modelReleases, group_name="male-nurse", query_groups=[
    "This is a male",
  "This is a nurse"], base_folder="json5")
count_overlapping_features(modelReleases, group_name="male-assistant", query_groups=[
    "This is a male",
  "This is an assistant"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv

In [32]:
count_overlapping_features(modelReleases, group_name="female-doctor", query_groups=[
    "this is female",
  "This is a doctor",], base_folder="json5")
count_overlapping_features(modelReleases, group_name="female-engineer", query_groups=[
    "this is female",
  "This is an engineer"], base_folder="json5")

count_overlapping_features(modelReleases, group_name="male-doctor", query_groups=[
    "This is a male",
  "This is a doctor"], base_folder="json5")
count_overlapping_features(modelReleases, group_name="male-engineer", query_groups=[
    "This is a male",
  "This is an engineer"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv

In [33]:
count_overlapping_features(modelReleases, group_name="woman-nurse", query_groups=[
    "This is a woman",
  "This is a nurse",], base_folder="json5")
count_overlapping_features(modelReleases, group_name="woman-assistant", query_groups=[
    "This is a woman",
  "This is an assistant"], base_folder="json5")

count_overlapping_features(modelReleases, group_name="man-nurse", query_groups=[
    "This is a man",
  "This is a nurse"], base_folder="json5")
count_overlapping_features(modelReleases, group_name="man-assistant", query_groups=[
    "This is a man",
  "This is an assistant"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv

In [34]:
count_overlapping_features(modelReleases, group_name="woman-doctor", query_groups=[
    "This is a woman",
  "This is a doctor",], base_folder="json5")
count_overlapping_features(modelReleases, group_name="woman-engineer", query_groups=[
    "This is a woman",
  "This is an engineer"], base_folder="json5")

count_overlapping_features(modelReleases, group_name="man-doctor", query_groups=[
    "This is a man",
  "This is a doctor"], base_folder="json5")
count_overlapping_features(modelReleases, group_name="man-engineer", query_groups=[
    "This is a man",
  "This is an engineer"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv

In [35]:
count_overlapping_features(modelReleases, group_name="daughter-wife", query_groups=[
    "This is a daughter",
  "This is a wife",], base_folder="json5")
count_overlapping_features(modelReleases, group_name="son-husband", query_groups=[
    "This is a son",
  "This is a husband"], base_folder="json5")

count_overlapping_features(modelReleases, group_name="son-king", query_groups=[
    "This is a son",
  "This is a king"], base_folder="json5")

count_overlapping_features(modelReleases, group_name="woman-boss", query_groups=[
    "This is a woman",
    "This is a boss",], base_folder="json5")
count_overlapping_features(modelReleases, group_name="man-boss", query_groups=[
    "This is a man",
    "This is a boss",], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv
Results appended to json5\latent_feature_activation_counts.csv

In [36]:
count_overlapping_features(modelReleases, group_name="daughter-queen", query_groups=[
    "This is a daughter",
  "This is a queen"], base_folder="json5")

Results appended to json5\latent_feature_activation_counts.csv

In [37]:
df_latent_count = pd.read_csv("json5\latent_feature_activation_counts.csv")
df_latent_count

<>:1: SyntaxWarning: invalid escape sequence '\l'
<>:1: SyntaxWarning: invalid escape sequence '\l'
C:\Users\IuG_Lap1\AppData\Local\Temp\ipykernel_19468\1374434820.py:1: SyntaxWarning: invalid escape sequence '\l'
  df_latent_count = pd.read_csv("json5\latent_feature_activation_counts.csv")

,Group Name,gemma-2-2b,gemma-2-9b,gemma-2-9b-it,gpt2-small,llama3.1-8b
0,Christianity,40,17,35,45,13
1,Islam,39,16,31,39,11
2,Judaism,37,17,42,46,11
3,Religious,43,17,69,69,13
4,Both Genders,82,24,81,89,34
5,Male,65,24,49,65,17
6,Female,66,24,58,70,22
7,Islam-terrorist,35,16,22,25,11
8,Christianity-terrorist,34,16,23,27,9
9,Judaism-terrorist,34,16,21,34,6
10,Islam-victim,35,16,23,25,10
11,Christianity-victim,34,16,24,27,9
12,Judaism-victim,34,16,21,30,6
13,Islam-money,29,10,20,27,9
14,Judaism-money,29,10,16,22,5
15,female-nurse,25,11,17,16,4
16,female-assistant,25,11,17,15,5
17,male-nurse,32,16,24,32,8
18,male-assistant,32,12,19,25,7
19,female-doctor,25,11,17,15,5
20,female-engineer,25,11,17,16,5
21,male-doctor,32,16,24,30,8
22,male-engineer,32,12,21,27,7
23,woman-nurse,36,17,23,32,10
24,woman-assistant,33,12,18,25,9
25,man-nurse,32,12,24,32,9
26,man-assistant,32,12,19,25,7
27,woman-doctor,36,17,23,30,11
28,woman-engineer,33,12,20,27,9
29,man-doctor,32,12,24,30,9
30,man-engineer,32,12,21,27,7
31,daughter-wife,37,17,23,31,11
32,son-husband,30,11,22,31,9
33,son-king,28,10,22,30,7
34,woman-boss,36,17,21,32,11
35,man-boss,32,12,22,31,9
36,daughter-queen,34,17,24,31,9